# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = testqmake

HEADERS = \
   $$PWD/ext/bcmath/libbcmath/src/bcmath.h \
   $$PWD/ext/bcmath/libbcmath/src/config.h \
   $$PWD/ext/bcmath/libbcmath/src/private.h \
   $$PWD/ext/bcmath/libbcmath/acconfig.h \
   $$PWD/ext/bcmath/php_bcmath.h \
   $$PWD/ext/bz2/php_bz2.h \
   $$PWD/ext/calendar/php_calendar.h \
   $$PWD/ext/calendar/sdncal.h \
   $$PWD/ext/com_dotnet/php_com_dotnet.h \
   $$PWD/ext/com_dotnet/php_com_dotnet_internal.h \
   $$PWD/ext/ctype/php_ctype.h \
   $$PWD/ext/curl/php_curl.h \
   $$PWD/ext/date/lib/astro.h \
   $$PWD/ext/date/lib/fallbackmap.h \
   $$PWD/ext/date/lib/timelib.h \
   $$PWD/ext/date/lib/timelib_config.h \
   $$PWD/ext/date/lib/timelib_private.h \
   $$PWD/ext/date/lib/timezonedb.h \
   $$PWD/ext/date/lib/timezonemap.h \
   $$PWD/ext/date/php_date.h \
   $$PWD/ext/dba/libcdb/cdb.h \
   $$PWD/ext/dba/libcdb/cdb_make.h \
   $$PWD/ext/dba/libcdb/uint32.h \
   $$PWD/ext/dba/libflatfile/flatfile.h \
   $$PWD/ext/dba/libinifile/inifile.h \
   $$PWD/ext/dba/php_cdb.h \
   $$PWD/ext/dba/php_db1.h \
   $$PWD/ext/dba/php_db2.h \
   $$PWD/ext/dba/php_db3.h \
   $$PWD/ext/dba/php_db4.h \
   $$PWD/ext/dba/php_dba.h \
   $$PWD/ext/dba/php_dbm.h \
   $$PWD/ext/dba/php_flatfile.h \
   $$PWD/ext/dba/php_gdbm.h \
   $$PWD/ext/dba/php_inifile.h \
   $$PWD/ext/dba/php_lmdb.h \
   $$PWD/ext/dba/php_ndbm.h \
   $$PWD/ext/dba/php_qdbm.h \
   $$PWD/ext/dba/php_tcadb.h \
   $$PWD/ext/dom/dom_ce.h \
   $$PWD/ext/dom/dom_fe.h \
   $$PWD/ext/dom/dom_properties.h \
   $$PWD/ext/dom/php_dom.h \
   $$PWD/ext/dom/xml_common.h \
   $$PWD/ext/enchant/php_enchant.h \
   $$PWD/ext/exif/php_exif.h \
   $$PWD/ext/fileinfo/libmagic/cdf.h \
   $$PWD/ext/fileinfo/libmagic/config.h \
   $$PWD/ext/fileinfo/libmagic/der.h \
   $$PWD/ext/fileinfo/libmagic/elfclass.h \
   $$PWD/ext/fileinfo/libmagic/file.h \
   $$PWD/ext/fileinfo/libmagic/magic.h \
   $$PWD/ext/fileinfo/libmagic/patchlevel.h \
   $$PWD/ext/fileinfo/libmagic/tar.h \
   $$PWD/ext/fileinfo/php_fileinfo.h \
   $$PWD/ext/filter/filter_private.h \
   $$PWD/ext/filter/php_filter.h \
   $$PWD/ext/ftp/ftp.h \
   $$PWD/ext/ftp/php_ftp.h \
   $$PWD/ext/gd/libgd/bmp.h \
   $$PWD/ext/gd/libgd/gd.h \
   $$PWD/ext/gd/libgd/gd_errors.h \
   $$PWD/ext/gd/libgd/gd_intern.h \
   $$PWD/ext/gd/libgd/gd_io.h \
   $$PWD/ext/gd/libgd/gdcache.h \
   $$PWD/ext/gd/libgd/gdfontg.h \
   $$PWD/ext/gd/libgd/gdfontl.h \
   $$PWD/ext/gd/libgd/gdfontmb.h \
   $$PWD/ext/gd/libgd/gdfonts.h \
   $$PWD/ext/gd/libgd/gdfontt.h \
   $$PWD/ext/gd/libgd/gdhelpers.h \
   $$PWD/ext/gd/libgd/jisx0208.h \
   $$PWD/ext/gd/libgd/wbmp.h \
   $$PWD/ext/gd/gd_compat.h \
   $$PWD/ext/gd/gdcache.h \
   $$PWD/ext/gd/php_gd.h \
   $$PWD/ext/gettext/php_gettext.h \
   $$PWD/ext/gmp/php_gmp.h \
   $$PWD/ext/hash/sha3/generic32lc/align.h \
   $$PWD/ext/hash/sha3/generic32lc/brg_endian.h \
   $$PWD/ext/hash/sha3/generic32lc/KeccakHash.h \
   $$PWD/ext/hash/sha3/generic32lc/KeccakP-1600-SnP.h \
   $$PWD/ext/hash/sha3/generic32lc/KeccakSponge.h \
   $$PWD/ext/hash/sha3/generic32lc/SnP-Relaned.h \
   $$PWD/ext/hash/sha3/generic64lc/align.h \
   $$PWD/ext/hash/sha3/generic64lc/brg_endian.h \
   $$PWD/ext/hash/sha3/generic64lc/KeccakHash.h \
   $$PWD/ext/hash/sha3/generic64lc/KeccakP-1600-opt64-config.h \
   $$PWD/ext/hash/sha3/generic64lc/KeccakP-1600-SnP.h \
   $$PWD/ext/hash/sha3/generic64lc/KeccakSponge.h \
   $$PWD/ext/hash/sha3/generic64lc/SnP-Relaned.h \
   $$PWD/ext/hash/php_hash.h \
   $$PWD/ext/hash/php_hash_adler32.h \
   $$PWD/ext/hash/php_hash_crc32.h \
   $$PWD/ext/hash/php_hash_crc32_tables.h \
   $$PWD/ext/hash/php_hash_fnv.h \
   $$PWD/ext/hash/php_hash_gost.h \
   $$PWD/ext/hash/php_hash_gost_tables.h \
   $$PWD/ext/hash/php_hash_haval.h \
   $$PWD/ext/hash/php_hash_joaat.h \
   $$PWD/ext/hash/php_hash_md.h \
   $$PWD/ext/hash/php_hash_ripemd.h \
   $$PWD/ext/hash/php_hash_sha.h \
   $$PWD/ext/hash/php_hash_sha3.h \
   $$PWD/ext/hash/php_hash_snefru.h \
   $$PWD/ext/hash/php_hash_snefru_tables.h \
   $$PWD/ext/hash/php_hash_tiger.h \
   $$PWD/ext/hash/php_hash_tiger_tables.h \
   $$PWD/ext/hash/php_hash_whirlpool.h \
   $$PWD/ext/hash/php_hash_whirlpool_tables.h \
   $$PWD/ext/iconv/ext/iconv/php_have_bsd_iconv.h \
   $$PWD/ext/iconv/ext/iconv/php_have_glibc_iconv.h \
   $$PWD/ext/iconv/ext/iconv/php_have_ibm_iconv.h \
   $$PWD/ext/iconv/ext/iconv/php_have_iconv.h \
   $$PWD/ext/iconv/ext/iconv/php_have_libiconv.h \
   $$PWD/ext/iconv/ext/iconv/php_iconv_aliased_libiconv.h \
   $$PWD/ext/iconv/ext/iconv/php_iconv_broken_ignore.h \
   $$PWD/ext/iconv/ext/iconv/php_iconv_supports_errno.h \
   $$PWD/ext/iconv/ext/iconv/php_php_iconv_h_path.h \
   $$PWD/ext/iconv/ext/iconv/php_php_iconv_impl.h \
   $$PWD/ext/iconv/config.h \
   $$PWD/ext/iconv/php_have_bsd_iconv.h \
   $$PWD/ext/iconv/php_have_glibc_iconv.h \
   $$PWD/ext/iconv/php_have_ibm_iconv.h \
   $$PWD/ext/iconv/php_have_iconv.h \
   $$PWD/ext/iconv/php_have_libiconv.h \
   $$PWD/ext/iconv/php_iconv.h \
   $$PWD/ext/iconv/php_iconv_aliased_libiconv.h \
   $$PWD/ext/iconv/php_iconv_broken_ignore.h \
   $$PWD/ext/iconv/php_iconv_supports_errno.h \
   $$PWD/ext/iconv/php_php_iconv_h_path.h \
   $$PWD/ext/iconv/php_php_iconv_impl.h \
   $$PWD/ext/imap/php_imap.h \
   $$PWD/ext/interbase/php_ibase_includes.h \
   $$PWD/ext/interbase/php_interbase.h \
   $$PWD/ext/intl/breakiterator/breakiterator_class.h \
   $$PWD/ext/intl/breakiterator/breakiterator_iterators.h \
   $$PWD/ext/intl/breakiterator/breakiterator_methods.h \
   $$PWD/ext/intl/breakiterator/codepointiterator_internal.h \
   $$PWD/ext/intl/breakiterator/codepointiterator_methods.h \
   $$PWD/ext/intl/breakiterator/rulebasedbreakiterator_methods.h \
   $$PWD/ext/intl/calendar/calendar_class.h \
   $$PWD/ext/intl/calendar/calendar_methods.h \
   $$PWD/ext/intl/calendar/gregoriancalendar_methods.h \
   $$PWD/ext/intl/collator/collator.h \
   $$PWD/ext/intl/collator/collator_attr.h \
   $$PWD/ext/intl/collator/collator_class.h \
   $$PWD/ext/intl/collator/collator_compare.h \
   $$PWD/ext/intl/collator/collator_convert.h \
   $$PWD/ext/intl/collator/collator_create.h \
   $$PWD/ext/intl/collator/collator_error.h \
   $$PWD/ext/intl/collator/collator_is_numeric.h \
   $$PWD/ext/intl/collator/collator_locale.h \
   $$PWD/ext/intl/collator/collator_sort.h \
   $$PWD/ext/intl/common/common_date.h \
   $$PWD/ext/intl/common/common_enum.h \
   $$PWD/ext/intl/common/common_error.h \
   $$PWD/ext/intl/converter/converter.h \
   $$PWD/ext/intl/dateformat/dateformat.h \
   $$PWD/ext/intl/dateformat/dateformat_attr.h \
   $$PWD/ext/intl/dateformat/dateformat_attrcpp.h \
   $$PWD/ext/intl/dateformat/dateformat_class.h \
   $$PWD/ext/intl/dateformat/dateformat_create.h \
   $$PWD/ext/intl/dateformat/dateformat_data.h \
   $$PWD/ext/intl/dateformat/dateformat_format.h \
   $$PWD/ext/intl/dateformat/dateformat_format_object.h \
   $$PWD/ext/intl/dateformat/dateformat_helpers.h \
   $$PWD/ext/intl/dateformat/dateformat_parse.h \
   $$PWD/ext/intl/formatter/formatter.h \
   $$PWD/ext/intl/formatter/formatter_attr.h \
   $$PWD/ext/intl/formatter/formatter_class.h \
   $$PWD/ext/intl/formatter/formatter_data.h \
   $$PWD/ext/intl/formatter/formatter_format.h \
   $$PWD/ext/intl/formatter/formatter_main.h \
   $$PWD/ext/intl/formatter/formatter_parse.h \
   $$PWD/ext/intl/grapheme/grapheme.h \
   $$PWD/ext/intl/grapheme/grapheme_util.h \
   $$PWD/ext/intl/idn/idn.h \
   $$PWD/ext/intl/locale/locale.h \
   $$PWD/ext/intl/locale/locale_class.h \
   $$PWD/ext/intl/locale/locale_methods.h \
   $$PWD/ext/intl/msgformat/msgformat.h \
   $$PWD/ext/intl/msgformat/msgformat_attr.h \
   $$PWD/ext/intl/msgformat/msgformat_class.h \
   $$PWD/ext/intl/msgformat/msgformat_data.h \
   $$PWD/ext/intl/msgformat/msgformat_format.h \
   $$PWD/ext/intl/msgformat/msgformat_helpers.h \
   $$PWD/ext/intl/msgformat/msgformat_parse.h \
   $$PWD/ext/intl/normalizer/normalizer.h \
   $$PWD/ext/intl/normalizer/normalizer_class.h \
   $$PWD/ext/intl/normalizer/normalizer_normalize.h \
   $$PWD/ext/intl/resourcebundle/resourcebundle.h \
   $$PWD/ext/intl/resourcebundle/resourcebundle_class.h \
   $$PWD/ext/intl/resourcebundle/resourcebundle_iterator.h \
   $$PWD/ext/intl/spoofchecker/spoofchecker.h \
   $$PWD/ext/intl/spoofchecker/spoofchecker_class.h \
   $$PWD/ext/intl/spoofchecker/spoofchecker_create.h \
   $$PWD/ext/intl/spoofchecker/spoofchecker_main.h \
   $$PWD/ext/intl/timezone/timezone_class.h \
   $$PWD/ext/intl/timezone/timezone_methods.h \
   $$PWD/ext/intl/transliterator/transliterator.h \
   $$PWD/ext/intl/transliterator/transliterator_class.h \
   $$PWD/ext/intl/transliterator/transliterator_methods.h \
   $$PWD/ext/intl/uchar/ublockcode-enum.h \
   $$PWD/ext/intl/uchar/uchar.h \
   $$PWD/ext/intl/uchar/ucharcategory-enum.h \
   $$PWD/ext/intl/uchar/uchardirection-enum.h \
   $$PWD/ext/intl/uchar/uother-enum.h \
   $$PWD/ext/intl/uchar/uproperty-enum.h \
   $$PWD/ext/intl/intl_common.h \
   $$PWD/ext/intl/intl_convert.h \
   $$PWD/ext/intl/intl_convertcpp.h \
   $$PWD/ext/intl/intl_cppshims.h \
   $$PWD/ext/intl/intl_data.h \
   $$PWD/ext/intl/intl_error.h \
   $$PWD/ext/intl/php_intl.h \
   $$PWD/ext/json/json_parser.tab.h \
   $$PWD/ext/json/php_json.h \
   $$PWD/ext/json/php_json_encoder.h \
   $$PWD/ext/json/php_json_parser.h \
   $$PWD/ext/json/php_json_scanner.h \
   $$PWD/ext/json/php_json_scanner_defs.h \
   $$PWD/ext/ldap/php_ldap.h \
   $$PWD/ext/libxml/php_libxml.h \
   $$PWD/ext/mbstring/libmbfl/filters/cp932_table.h \
   $$PWD/ext/mbstring/libmbfl/filters/emoji2uni.h \
   $$PWD/ext/mbstring/libmbfl/filters/html_entities.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_7bit.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_armscii8.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_ascii.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_base64.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_big5.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_byte2.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_byte4.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp1251.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp1252.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp1254.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp5022x.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp51932.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp850.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp866.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp932.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp936.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_euc_cn.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_euc_jp.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_euc_jp_2004.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_euc_jp_win.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_euc_kr.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_euc_tw.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_gb18030.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_htmlent.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_hz.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso2022_jp_ms.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso2022_kr.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso2022jp_2004.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso2022jp_mobile.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_1.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_10.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_13.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_14.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_15.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_16.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_2.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_3.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_4.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_5.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_6.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_7.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_8.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_9.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_jis.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_koi8r.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_koi8u.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_qprint.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_sjis.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_sjis_2004.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_sjis_mac.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_sjis_mobile.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_sjis_open.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_tl_jisx0201_jisx0208.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_ucs2.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_ucs4.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_uhc.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_utf16.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_utf32.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_utf7.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_utf7imap.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_utf8.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_utf8_mobile.h \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_uuencode.h \
   $$PWD/ext/mbstring/libmbfl/filters/sjis_mac2uni.h \
   $$PWD/ext/mbstring/libmbfl/filters/translit_kana_jisx0201_jisx0208.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_prop.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_armscii8.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_big5.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_cns11643.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_cp1251.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_cp1252.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_cp1254.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_cp850.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_cp866.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_cp932_ext.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_cp936.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_gb18030.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_iso8859_10.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_iso8859_13.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_iso8859_14.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_iso8859_15.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_iso8859_16.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_iso8859_2.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_iso8859_3.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_iso8859_4.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_iso8859_5.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_iso8859_6.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_iso8859_7.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_iso8859_8.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_iso8859_9.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_jis.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_jis2004.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_koi8r.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_koi8u.h \
   $$PWD/ext/mbstring/libmbfl/filters/unicode_table_uhc.h \
   $$PWD/ext/mbstring/libmbfl/mbfl/eaw_table.h \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfilter.h \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfilter_8bit.h \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfilter_pass.h \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfilter_wchar.h \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_allocators.h \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_consts.h \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_convert.h \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_defs.h \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_encoding.h \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_filter_output.h \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_ident.h \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_language.h \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_memory_device.h \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_string.h \
   $$PWD/ext/mbstring/libmbfl/nls/nls_de.h \
   $$PWD/ext/mbstring/libmbfl/nls/nls_en.h \
   $$PWD/ext/mbstring/libmbfl/nls/nls_hy.h \
   $$PWD/ext/mbstring/libmbfl/nls/nls_ja.h \
   $$PWD/ext/mbstring/libmbfl/nls/nls_kr.h \
   $$PWD/ext/mbstring/libmbfl/nls/nls_neutral.h \
   $$PWD/ext/mbstring/libmbfl/nls/nls_ru.h \
   $$PWD/ext/mbstring/libmbfl/nls/nls_tr.h \
   $$PWD/ext/mbstring/libmbfl/nls/nls_ua.h \
   $$PWD/ext/mbstring/libmbfl/nls/nls_uni.h \
   $$PWD/ext/mbstring/libmbfl/nls/nls_zh.h \
   $$PWD/ext/mbstring/libmbfl/config.h \
   $$PWD/ext/mbstring/oniguruma/src/config.h \
   $$PWD/ext/mbstring/oniguruma/src/oniggnu.h \
   $$PWD/ext/mbstring/oniguruma/src/onigposix.h \
   $$PWD/ext/mbstring/oniguruma/src/oniguruma.h \
   $$PWD/ext/mbstring/oniguruma/src/regenc.h \
   $$PWD/ext/mbstring/oniguruma/src/regint.h \
   $$PWD/ext/mbstring/oniguruma/src/regparse.h \
   $$PWD/ext/mbstring/oniguruma/src/st.h \
   $$PWD/ext/mbstring/oniguruma/oniguruma.h \
   $$PWD/ext/mbstring/config.h \
   $$PWD/ext/mbstring/mb_gpc.h \
   $$PWD/ext/mbstring/mbstring.h \
   $$PWD/ext/mbstring/php_mbregex.h \
   $$PWD/ext/mbstring/php_onig_compat.h \
   $$PWD/ext/mbstring/php_unicode.h \
   $$PWD/ext/mbstring/unicode_data.h \
   $$PWD/ext/mysqli/mysqli_fe.h \
   $$PWD/ext/mysqli/mysqli_libmysql.h \
   $$PWD/ext/mysqli/mysqli_mysqlnd.h \
   $$PWD/ext/mysqli/mysqli_priv.h \
   $$PWD/ext/mysqli/php_mysqli.h \
   $$PWD/ext/mysqli/php_mysqli_structs.h \
   $$PWD/ext/mysqlnd/config-win.h \
   $$PWD/ext/mysqlnd/mysql_float_to_double.h \
   $$PWD/ext/mysqlnd/mysqlnd.h \
   $$PWD/ext/mysqlnd/mysqlnd_alloc.h \
   $$PWD/ext/mysqlnd/mysqlnd_auth.h \
   $$PWD/ext/mysqlnd/mysqlnd_block_alloc.h \
   $$PWD/ext/mysqlnd/mysqlnd_charset.h \
   $$PWD/ext/mysqlnd/mysqlnd_commands.h \
   $$PWD/ext/mysqlnd/mysqlnd_connection.h \
   $$PWD/ext/mysqlnd/mysqlnd_debug.h \
   $$PWD/ext/mysqlnd/mysqlnd_enum_n_def.h \
   $$PWD/ext/mysqlnd/mysqlnd_ext_plugin.h \
   $$PWD/ext/mysqlnd/mysqlnd_libmysql_compat.h \
   $$PWD/ext/mysqlnd/mysqlnd_plugin.h \
   $$PWD/ext/mysqlnd/mysqlnd_portability.h \
   $$PWD/ext/mysqlnd/mysqlnd_priv.h \
   $$PWD/ext/mysqlnd/mysqlnd_protocol_frame_codec.h \
   $$PWD/ext/mysqlnd/mysqlnd_ps.h \
   $$PWD/ext/mysqlnd/mysqlnd_read_buffer.h \
   $$PWD/ext/mysqlnd/mysqlnd_result.h \
   $$PWD/ext/mysqlnd/mysqlnd_result_meta.h \
   $$PWD/ext/mysqlnd/mysqlnd_reverse_api.h \
   $$PWD/ext/mysqlnd/mysqlnd_statistics.h \
   $$PWD/ext/mysqlnd/mysqlnd_structs.h \
   $$PWD/ext/mysqlnd/mysqlnd_vio.h \
   $$PWD/ext/mysqlnd/mysqlnd_wireprotocol.h \
   $$PWD/ext/mysqlnd/php_mysqlnd.h \
   $$PWD/ext/oci8/php_oci8.h \
   $$PWD/ext/oci8/php_oci8_int.h \
   $$PWD/ext/odbc/php_birdstep.h \
   $$PWD/ext/odbc/php_odbc.h \
   $$PWD/ext/odbc/php_odbc_includes.h \
   $$PWD/ext/opcache/Optimizer/scdf.h \
   $$PWD/ext/opcache/Optimizer/zend_call_graph.h \
   $$PWD/ext/opcache/Optimizer/zend_cfg.h \
   $$PWD/ext/opcache/Optimizer/zend_dfg.h \
   $$PWD/ext/opcache/Optimizer/zend_dump.h \
   $$PWD/ext/opcache/Optimizer/zend_func_info.h \
   $$PWD/ext/opcache/Optimizer/zend_inference.h \
   $$PWD/ext/opcache/Optimizer/zend_optimizer.h \
   $$PWD/ext/opcache/Optimizer/zend_optimizer_internal.h \
   $$PWD/ext/opcache/Optimizer/zend_ssa.h \
   $$PWD/ext/opcache/Optimizer/zend_worklist.h \
   $$PWD/ext/opcache/zend_accelerator_blacklist.h \
   $$PWD/ext/opcache/zend_accelerator_debug.h \
   $$PWD/ext/opcache/zend_accelerator_hash.h \
   $$PWD/ext/opcache/zend_accelerator_module.h \
   $$PWD/ext/opcache/zend_accelerator_util_funcs.h \
   $$PWD/ext/opcache/zend_file_cache.h \
   $$PWD/ext/opcache/zend_persist.h \
   $$PWD/ext/opcache/zend_shared_alloc.h \
   $$PWD/ext/opcache/ZendAccelerator.h \
   $$PWD/ext/openssl/config.h \
   $$PWD/ext/openssl/php_openssl.h \
   $$PWD/ext/pcntl/php_pcntl.h \
   $$PWD/ext/pcntl/php_signal.h \
   $$PWD/ext/pcre/pcrelib/sljit/sljitConfig.h \
   $$PWD/ext/pcre/pcrelib/sljit/sljitConfigInternal.h \
   $$PWD/ext/pcre/pcrelib/sljit/sljitLir.h \
   $$PWD/ext/pcre/pcrelib/config.h \
   $$PWD/ext/pcre/pcrelib/pcre.h \
   $$PWD/ext/pcre/pcrelib/pcre_internal.h \
   $$PWD/ext/pcre/pcrelib/pcreposix.h \
   $$PWD/ext/pcre/pcrelib/ucp.h \
   $$PWD/ext/pcre/php_pcre.h \
   $$PWD/ext/pdo/php_pdo.h \
   $$PWD/ext/pdo/php_pdo_driver.h \
   $$PWD/ext/pdo/php_pdo_error.h \
   $$PWD/ext/pdo/php_pdo_int.h \
   $$PWD/ext/pdo_dblib/php_pdo_dblib.h \
   $$PWD/ext/pdo_dblib/php_pdo_dblib_int.h \
   $$PWD/ext/pdo_firebird/php_pdo_firebird.h \
   $$PWD/ext/pdo_firebird/php_pdo_firebird_int.h \
   $$PWD/ext/pdo_mysql/php_pdo_mysql.h \
   $$PWD/ext/pdo_mysql/php_pdo_mysql_int.h \
   $$PWD/ext/pdo_mysql/php_pdo_mysql_sqlstate.h \
   $$PWD/ext/pdo_oci/php_pdo_oci.h \
   $$PWD/ext/pdo_oci/php_pdo_oci_int.h \
   $$PWD/ext/pdo_odbc/php_pdo_odbc.h \
   $$PWD/ext/pdo_odbc/php_pdo_odbc_int.h \
   $$PWD/ext/pdo_pgsql/php_pdo_pgsql.h \
   $$PWD/ext/pdo_pgsql/php_pdo_pgsql_int.h \
   $$PWD/ext/pdo_sqlite/php_pdo_sqlite.h \
   $$PWD/ext/pdo_sqlite/php_pdo_sqlite_int.h \
   $$PWD/ext/pgsql/php_pgsql.h \
   $$PWD/ext/phar/dirstream.h \
   $$PWD/ext/phar/func_interceptors.h \
   $$PWD/ext/phar/phar_internal.h \
   $$PWD/ext/phar/pharzip.h \
   $$PWD/ext/phar/php_phar.h \
   $$PWD/ext/phar/stream.h \
   $$PWD/ext/phar/stub.h \
   $$PWD/ext/phar/tar.h \
   $$PWD/ext/posix/php_posix.h \
   $$PWD/ext/pspell/php_pspell.h \
   $$PWD/ext/readline/php_readline.h \
   $$PWD/ext/readline/readline_cli.h \
   $$PWD/ext/recode/php_recode.h \
   $$PWD/ext/reflection/php_reflection.h \
   $$PWD/ext/session/mod_files.h \
   $$PWD/ext/session/mod_mm.h \
   $$PWD/ext/session/mod_user.h \
   $$PWD/ext/session/php_session.h \
   $$PWD/ext/shmop/php_shmop.h \
   $$PWD/ext/simplexml/php_simplexml.h \
   $$PWD/ext/simplexml/php_simplexml_exports.h \
   $$PWD/ext/simplexml/sxe.h \
   $$PWD/ext/skeleton/php_skeleton.h \
   $$PWD/ext/snmp/php_snmp.h \
   $$PWD/ext/soap/php_encoding.h \
   $$PWD/ext/soap/php_http.h \
   $$PWD/ext/soap/php_packet_soap.h \
   $$PWD/ext/soap/php_schema.h \
   $$PWD/ext/soap/php_sdl.h \
   $$PWD/ext/soap/php_soap.h \
   $$PWD/ext/soap/php_xml.h \
   $$PWD/ext/sockets/conversions.h \
   $$PWD/ext/sockets/multicast.h \
   $$PWD/ext/sockets/php_sockets.h \
   $$PWD/ext/sockets/sendrecvmsg.h \
   $$PWD/ext/sockets/sockaddr_conv.h \
   $$PWD/ext/sockets/unix_socket_constants.h \
   $$PWD/ext/sockets/win32_socket_constants.h \
   $$PWD/ext/sockets/windows_common.h \
   $$PWD/ext/sodium/php_libsodium.h \
   $$PWD/ext/spl/php_spl.h \
   $$PWD/ext/spl/spl_array.h \
   $$PWD/ext/spl/spl_directory.h \
   $$PWD/ext/spl/spl_dllist.h \
   $$PWD/ext/spl/spl_engine.h \
   $$PWD/ext/spl/spl_exceptions.h \
   $$PWD/ext/spl/spl_fixedarray.h \
   $$PWD/ext/spl/spl_functions.h \
   $$PWD/ext/spl/spl_heap.h \
   $$PWD/ext/spl/spl_iterators.h \
   $$PWD/ext/spl/spl_observer.h \
   $$PWD/ext/sqlite3/libsqlite/sqlite3.h \
   $$PWD/ext/sqlite3/libsqlite/sqlite3ext.h \
   $$PWD/ext/sqlite3/php_sqlite3.h \
   $$PWD/ext/sqlite3/php_sqlite3_structs.h \
   $$PWD/ext/standard/base64.h \
   $$PWD/ext/standard/basic_functions.h \
   $$PWD/ext/standard/crc32.h \
   $$PWD/ext/standard/credits.h \
   $$PWD/ext/standard/credits_ext.h \
   $$PWD/ext/standard/credits_sapi.h \
   $$PWD/ext/standard/crypt_blowfish.h \
   $$PWD/ext/standard/crypt_freesec.h \
   $$PWD/ext/standard/css.h \
   $$PWD/ext/standard/cyr_convert.h \
   $$PWD/ext/standard/datetime.h \
   $$PWD/ext/standard/dl.h \
   $$PWD/ext/standard/exec.h \
   $$PWD/ext/standard/file.h \
   $$PWD/ext/standard/flock_compat.h \
   $$PWD/ext/standard/fsock.h \
   $$PWD/ext/standard/head.h \
   $$PWD/ext/standard/html.h \
   $$PWD/ext/standard/html_tables.h \
   $$PWD/ext/standard/info.h \
   $$PWD/ext/standard/md5.h \
   $$PWD/ext/standard/microtime.h \
   $$PWD/ext/standard/pack.h \
   $$PWD/ext/standard/pageinfo.h \
   $$PWD/ext/standard/php_array.h \
   $$PWD/ext/standard/php_assert.h \
   $$PWD/ext/standard/php_browscap.h \
   $$PWD/ext/standard/php_crypt.h \
   $$PWD/ext/standard/php_crypt_r.h \
   $$PWD/ext/standard/php_dir.h \
   $$PWD/ext/standard/php_dns.h \
   $$PWD/ext/standard/php_ext_syslog.h \
   $$PWD/ext/standard/php_filestat.h \
   $$PWD/ext/standard/php_fopen_wrappers.h \
   $$PWD/ext/standard/php_ftok.h \
   $$PWD/ext/standard/php_http.h \
   $$PWD/ext/standard/php_image.h \
   $$PWD/ext/standard/php_incomplete_class.h \
   $$PWD/ext/standard/php_iptc.h \
   $$PWD/ext/standard/php_lcg.h \
   $$PWD/ext/standard/php_link.h \
   $$PWD/ext/standard/php_mail.h \
   $$PWD/ext/standard/php_math.h \
   $$PWD/ext/standard/php_metaphone.h \
   $$PWD/ext/standard/php_mt_rand.h \
   $$PWD/ext/standard/php_password.h \
   $$PWD/ext/standard/php_rand.h \
   $$PWD/ext/standard/php_random.h \
   $$PWD/ext/standard/php_smart_string.h \
   $$PWD/ext/standard/php_smart_string_public.h \
   $$PWD/ext/standard/php_standard.h \
   $$PWD/ext/standard/php_string.h \
   $$PWD/ext/standard/php_type.h \
   $$PWD/ext/standard/php_uuencode.h \
   $$PWD/ext/standard/php_var.h \
   $$PWD/ext/standard/php_versioning.h \
   $$PWD/ext/standard/proc_open.h \
   $$PWD/ext/standard/quot_print.h \
   $$PWD/ext/standard/scanf.h \
   $$PWD/ext/standard/sha1.h \
   $$PWD/ext/standard/streamsfuncs.h \
   $$PWD/ext/standard/uniqid.h \
   $$PWD/ext/standard/url.h \
   $$PWD/ext/standard/url_scanner_ex.h \
   $$PWD/ext/standard/winver.h \
   $$PWD/ext/sysvmsg/php_sysvmsg.h \
   $$PWD/ext/sysvsem/php_sysvsem.h \
   $$PWD/ext/sysvshm/php_sysvshm.h \
   $$PWD/ext/tidy/php_tidy.h \
   $$PWD/ext/tokenizer/php_tokenizer.h \
   $$PWD/ext/wddx/php_wddx.h \
   $$PWD/ext/wddx/php_wddx_api.h \
   $$PWD/ext/xml/expat_compat.h \
   $$PWD/ext/xml/php_xml.h \
   $$PWD/ext/xmlreader/php_xmlreader.h \
   $$PWD/ext/xmlrpc/libxmlrpc/base64.h \
   $$PWD/ext/xmlrpc/libxmlrpc/encodings.h \
   $$PWD/ext/xmlrpc/libxmlrpc/queue.h \
   $$PWD/ext/xmlrpc/libxmlrpc/simplestring.h \
   $$PWD/ext/xmlrpc/libxmlrpc/system_methods_private.h \
   $$PWD/ext/xmlrpc/libxmlrpc/xml_element.h \
   $$PWD/ext/xmlrpc/libxmlrpc/xml_to_dandarpc.h \
   $$PWD/ext/xmlrpc/libxmlrpc/xml_to_soap.h \
   $$PWD/ext/xmlrpc/libxmlrpc/xml_to_xmlrpc.h \
   $$PWD/ext/xmlrpc/libxmlrpc/xmlrpc.h \
   $$PWD/ext/xmlrpc/libxmlrpc/xmlrpc_introspection.h \
   $$PWD/ext/xmlrpc/libxmlrpc/xmlrpc_introspection_private.h \
   $$PWD/ext/xmlrpc/libxmlrpc/xmlrpc_private.h \
   $$PWD/ext/xmlrpc/php_xmlrpc.h \
   $$PWD/ext/xmlwriter/php_xmlwriter.h \
   $$PWD/ext/xsl/php_xsl.h \
   $$PWD/ext/xsl/xsl_fe.h \
   $$PWD/ext/zend_test/php_test.h \
   $$PWD/ext/zip/lib/config.h \
   $$PWD/ext/zip/lib/php_zip_config.w32.h \
   $$PWD/ext/zip/lib/zip.h \
   $$PWD/ext/zip/lib/zipconf.h \
   $$PWD/ext/zip/lib/zipint.h \
   $$PWD/ext/zip/lib/zipwin32.h \
   $$PWD/ext/zip/config.h \
   $$PWD/ext/zip/php_zip.h \
   $$PWD/ext/zlib/php_zlib.h \
   $$PWD/main/streams/php_stream_context.h \
   $$PWD/main/streams/php_stream_filter_api.h \
   $$PWD/main/streams/php_stream_glob_wrapper.h \
   $$PWD/main/streams/php_stream_mmap.h \
   $$PWD/main/streams/php_stream_plain_wrapper.h \
   $$PWD/main/streams/php_stream_transport.h \
   $$PWD/main/streams/php_stream_userspace.h \
   $$PWD/main/streams/php_streams_int.h \
   $$PWD/main/build-defs.h \
   $$PWD/main/fastcgi.h \
   $$PWD/main/fopen_wrappers.h \
   $$PWD/main/http_status_codes.h \
   $$PWD/main/php.h \
   $$PWD/main/php_compat.h \
   $$PWD/main/php_config.h \
   $$PWD/main/php_content_types.h \
   $$PWD/main/php_getopt.h \
   $$PWD/main/php_globals.h \
   $$PWD/main/php_ini.h \
   $$PWD/main/php_main.h \
   $$PWD/main/php_memory_streams.h \
   $$PWD/main/php_network.h \
   $$PWD/main/php_open_temporary_file.h \
   $$PWD/main/php_output.h \
   $$PWD/main/php_reentrancy.h \
   $$PWD/main/php_scandir.h \
   $$PWD/main/php_stdint.h \
   $$PWD/main/php_streams.h \
   $$PWD/main/php_syslog.h \
   $$PWD/main/php_ticks.h \
   $$PWD/main/php_variables.h \
   $$PWD/main/php_version.h \
   $$PWD/main/rfc1867.h \
   $$PWD/main/SAPI.h \
   $$PWD/main/snprintf.h \
   $$PWD/main/spprintf.h \
   $$PWD/sapi/apache2handler/php_apache.h \
   $$PWD/sapi/cli/cli.h \
   $$PWD/sapi/cli/mime_type_map.h \
   $$PWD/sapi/cli/php_cli_process_title.h \
   $$PWD/sapi/cli/php_cli_server.h \
   $$PWD/sapi/cli/php_http_parser.h \
   $$PWD/sapi/cli/ps_title.h \
   $$PWD/sapi/embed/php_embed.h \
   $$PWD/sapi/fpm/fpm/events/devpoll.h \
   $$PWD/sapi/fpm/fpm/events/epoll.h \
   $$PWD/sapi/fpm/fpm/events/kqueue.h \
   $$PWD/sapi/fpm/fpm/events/poll.h \
   $$PWD/sapi/fpm/fpm/events/port.h \
   $$PWD/sapi/fpm/fpm/events/select.h \
   $$PWD/sapi/fpm/fpm/fpm.h \
   $$PWD/sapi/fpm/fpm/fpm_arrays.h \
   $$PWD/sapi/fpm/fpm/fpm_atomic.h \
   $$PWD/sapi/fpm/fpm/fpm_children.h \
   $$PWD/sapi/fpm/fpm/fpm_cleanup.h \
   $$PWD/sapi/fpm/fpm/fpm_clock.h \
   $$PWD/sapi/fpm/fpm/fpm_conf.h \
   $$PWD/sapi/fpm/fpm/fpm_config.h \
   $$PWD/sapi/fpm/fpm/fpm_env.h \
   $$PWD/sapi/fpm/fpm/fpm_events.h \
   $$PWD/sapi/fpm/fpm/fpm_log.h \
   $$PWD/sapi/fpm/fpm/fpm_php.h \
   $$PWD/sapi/fpm/fpm/fpm_php_trace.h \
   $$PWD/sapi/fpm/fpm/fpm_process_ctl.h \
   $$PWD/sapi/fpm/fpm/fpm_request.h \
   $$PWD/sapi/fpm/fpm/fpm_scoreboard.h \
   $$PWD/sapi/fpm/fpm/fpm_shm.h \
   $$PWD/sapi/fpm/fpm/fpm_signals.h \
   $$PWD/sapi/fpm/fpm/fpm_sockets.h \
   $$PWD/sapi/fpm/fpm/fpm_status.h \
   $$PWD/sapi/fpm/fpm/fpm_stdio.h \
   $$PWD/sapi/fpm/fpm/fpm_str.h \
   $$PWD/sapi/fpm/fpm/fpm_systemd.h \
   $$PWD/sapi/fpm/fpm/fpm_trace.h \
   $$PWD/sapi/fpm/fpm/fpm_unix.h \
   $$PWD/sapi/fpm/fpm/fpm_worker_pool.h \
   $$PWD/sapi/fpm/fpm/zlog.h \
   $$PWD/sapi/fpm/config.h \
   $$PWD/sapi/litespeed/lsapidef.h \
   $$PWD/sapi/litespeed/lsapilib.h \
   $$PWD/sapi/litespeed/lscriu.h \
   $$PWD/sapi/phpdbg/phpdbg.h \
   $$PWD/sapi/phpdbg/phpdbg_bp.h \
   $$PWD/sapi/phpdbg/phpdbg_break.h \
   $$PWD/sapi/phpdbg/phpdbg_btree.h \
   $$PWD/sapi/phpdbg/phpdbg_cmd.h \
   $$PWD/sapi/phpdbg/phpdbg_eol.h \
   $$PWD/sapi/phpdbg/phpdbg_frame.h \
   $$PWD/sapi/phpdbg/phpdbg_help.h \
   $$PWD/sapi/phpdbg/phpdbg_info.h \
   $$PWD/sapi/phpdbg/phpdbg_io.h \
   $$PWD/sapi/phpdbg/phpdbg_lexer.h \
   $$PWD/sapi/phpdbg/phpdbg_list.h \
   $$PWD/sapi/phpdbg/phpdbg_opcode.h \
   $$PWD/sapi/phpdbg/phpdbg_out.h \
   $$PWD/sapi/phpdbg/phpdbg_parser.h \
   $$PWD/sapi/phpdbg/phpdbg_print.h \
   $$PWD/sapi/phpdbg/phpdbg_prompt.h \
   $$PWD/sapi/phpdbg/phpdbg_rinit_hook.h \
   $$PWD/sapi/phpdbg/phpdbg_set.h \
   $$PWD/sapi/phpdbg/phpdbg_sigio_win32.h \
   $$PWD/sapi/phpdbg/phpdbg_sigsafe.h \
   $$PWD/sapi/phpdbg/phpdbg_utils.h \
   $$PWD/sapi/phpdbg/phpdbg_wait.h \
   $$PWD/sapi/phpdbg/phpdbg_watch.h \
   $$PWD/sapi/phpdbg/phpdbg_webdata_transfer.h \
   $$PWD/sapi/phpdbg/phpdbg_win.h \
   $$PWD/TSRM/readdir.h \
   $$PWD/TSRM/TSRM.h \
   $$PWD/TSRM/tsrm_config.h \
   $$PWD/TSRM/tsrm_config.w32.h \
   $$PWD/TSRM/tsrm_config_common.h \
   $$PWD/TSRM/tsrm_strtok_r.h \
   $$PWD/TSRM/tsrm_win32.h \
   $$PWD/win32/codepage.h \
   $$PWD/win32/console.h \
   $$PWD/win32/fnmatch.h \
   $$PWD/win32/getrusage.h \
   $$PWD/win32/glob.h \
   $$PWD/win32/grp.h \
   $$PWD/win32/inet.h \
   $$PWD/win32/ioutil.h \
   $$PWD/win32/ipc.h \
   $$PWD/win32/nice.h \
   $$PWD/win32/param.h \
   $$PWD/win32/php_inttypes.h \
   $$PWD/win32/php_registry.h \
   $$PWD/win32/php_stdbool.h \
   $$PWD/win32/php_stdint.h \
   $$PWD/win32/php_win32_globals.h \
   $$PWD/win32/readdir.h \
   $$PWD/win32/resource.h \
   $$PWD/win32/select.h \
   $$PWD/win32/sendmail.h \
   $$PWD/win32/signal.h \
   $$PWD/win32/sockets.h \
   $$PWD/win32/syslog.h \
   $$PWD/win32/time.h \
   $$PWD/win32/unistd.h \
   $$PWD/win32/winutil.h \
   $$PWD/Zend/zend.h \
   $$PWD/Zend/zend_alloc.h \
   $$PWD/Zend/zend_alloc_sizes.h \
   $$PWD/Zend/zend_API.h \
   $$PWD/Zend/zend_arena.h \
   $$PWD/Zend/zend_ast.h \
   $$PWD/Zend/zend_bitset.h \
   $$PWD/Zend/zend_build.h \
   $$PWD/Zend/zend_builtin_functions.h \
   $$PWD/Zend/zend_closures.h \
   $$PWD/Zend/zend_compile.h \
   $$PWD/Zend/zend_config.h \
   $$PWD/Zend/zend_config.nw.h \
   $$PWD/Zend/zend_config.w32.h \
   $$PWD/Zend/zend_constants.h \
   $$PWD/Zend/zend_dtrace.h \
   $$PWD/Zend/zend_errors.h \
   $$PWD/Zend/zend_exceptions.h \
   $$PWD/Zend/zend_execute.h \
   $$PWD/Zend/zend_extensions.h \
   $$PWD/Zend/zend_float.h \
   $$PWD/Zend/zend_gc.h \
   $$PWD/Zend/zend_generators.h \
   $$PWD/Zend/zend_globals.h \
   $$PWD/Zend/zend_globals_macros.h \
   $$PWD/Zend/zend_hash.h \
   $$PWD/Zend/zend_highlight.h \
   $$PWD/Zend/zend_inheritance.h \
   $$PWD/Zend/zend_ini.h \
   $$PWD/Zend/zend_ini_parser.h \
   $$PWD/Zend/zend_ini_scanner.h \
   $$PWD/Zend/zend_ini_scanner_defs.h \
   $$PWD/Zend/zend_interfaces.h \
   $$PWD/Zend/zend_istdiostream.h \
   $$PWD/Zend/zend_iterators.h \
   $$PWD/Zend/zend_language_parser.h \
   $$PWD/Zend/zend_language_scanner.h \
   $$PWD/Zend/zend_language_scanner_defs.h \
   $$PWD/Zend/zend_list.h \
   $$PWD/Zend/zend_llist.h \
   $$PWD/Zend/zend_long.h \
   $$PWD/Zend/zend_modules.h \
   $$PWD/Zend/zend_multibyte.h \
   $$PWD/Zend/zend_multiply.h \
   $$PWD/Zend/zend_object_handlers.h \
   $$PWD/Zend/zend_objects.h \
   $$PWD/Zend/zend_objects_API.h \
   $$PWD/Zend/zend_operators.h \
   $$PWD/Zend/zend_portability.h \
   $$PWD/Zend/zend_ptr_stack.h \
   $$PWD/Zend/zend_range_check.h \
   $$PWD/Zend/zend_signal.h \
   $$PWD/Zend/zend_smart_str.h \
   $$PWD/Zend/zend_smart_str_public.h \
   $$PWD/Zend/zend_smart_string.h \
   $$PWD/Zend/zend_smart_string_public.h \
   $$PWD/Zend/zend_sort.h \
   $$PWD/Zend/zend_stack.h \
   $$PWD/Zend/zend_stream.h \
   $$PWD/Zend/zend_string.h \
   $$PWD/Zend/zend_strtod.h \
   $$PWD/Zend/zend_strtod_int.h \
   $$PWD/Zend/zend_ts_hash.h \
   $$PWD/Zend/zend_type_info.h \
   $$PWD/Zend/zend_types.h \
   $$PWD/Zend/zend_variables.h \
   $$PWD/Zend/zend_virtual_cwd.h \
   $$PWD/Zend/zend_vm.h \
   $$PWD/Zend/zend_vm_def.h \
   $$PWD/Zend/zend_vm_execute.h \
   $$PWD/Zend/zend_vm_opcodes.h

SOURCES = \
   $$PWD/ext/bcmath/libbcmath/src/add.c \
   $$PWD/ext/bcmath/libbcmath/src/compare.c \
   $$PWD/ext/bcmath/libbcmath/src/debug.c \
   $$PWD/ext/bcmath/libbcmath/src/div.c \
   $$PWD/ext/bcmath/libbcmath/src/divmod.c \
   $$PWD/ext/bcmath/libbcmath/src/doaddsub.c \
   $$PWD/ext/bcmath/libbcmath/src/init.c \
   $$PWD/ext/bcmath/libbcmath/src/int2num.c \
   $$PWD/ext/bcmath/libbcmath/src/nearzero.c \
   $$PWD/ext/bcmath/libbcmath/src/neg.c \
   $$PWD/ext/bcmath/libbcmath/src/num2long.c \
   $$PWD/ext/bcmath/libbcmath/src/num2str.c \
   $$PWD/ext/bcmath/libbcmath/src/outofmem.c \
   $$PWD/ext/bcmath/libbcmath/src/output.c \
   $$PWD/ext/bcmath/libbcmath/src/raise.c \
   $$PWD/ext/bcmath/libbcmath/src/raisemod.c \
   $$PWD/ext/bcmath/libbcmath/src/recmul.c \
   $$PWD/ext/bcmath/libbcmath/src/rmzero.c \
   $$PWD/ext/bcmath/libbcmath/src/rt.c \
   $$PWD/ext/bcmath/libbcmath/src/sqrt.c \
   $$PWD/ext/bcmath/libbcmath/src/str2num.c \
   $$PWD/ext/bcmath/libbcmath/src/sub.c \
   $$PWD/ext/bcmath/libbcmath/src/zero.c \
   $$PWD/ext/bcmath/bcmath.c \
   $$PWD/ext/bz2/bz2.c \
   $$PWD/ext/bz2/bz2_filter.c \
   $$PWD/ext/calendar/cal_unix.c \
   $$PWD/ext/calendar/calendar.c \
   $$PWD/ext/calendar/dow.c \
   $$PWD/ext/calendar/easter.c \
   $$PWD/ext/calendar/french.c \
   $$PWD/ext/calendar/gregor.c \
   $$PWD/ext/calendar/jewish.c \
   $$PWD/ext/calendar/julian.c \
   $$PWD/ext/com_dotnet/com_com.c \
   $$PWD/ext/com_dotnet/com_dotnet.c \
   $$PWD/ext/com_dotnet/com_extension.c \
   $$PWD/ext/com_dotnet/com_handlers.c \
   $$PWD/ext/com_dotnet/com_iterator.c \
   $$PWD/ext/com_dotnet/com_misc.c \
   $$PWD/ext/com_dotnet/com_olechar.c \
   $$PWD/ext/com_dotnet/com_persist.c \
   $$PWD/ext/com_dotnet/com_saproxy.c \
   $$PWD/ext/com_dotnet/com_typeinfo.c \
   $$PWD/ext/com_dotnet/com_variant.c \
   $$PWD/ext/com_dotnet/com_wrapper.c \
   $$PWD/ext/ctype/ctype.c \
   $$PWD/ext/curl/curl_file.c \
   $$PWD/ext/curl/interface.c \
   $$PWD/ext/curl/multi.c \
   $$PWD/ext/curl/share.c \
   $$PWD/ext/date/lib/astro.c \
   $$PWD/ext/date/lib/dow.c \
   $$PWD/ext/date/lib/interval.c \
   $$PWD/ext/date/lib/parse_date.c \
   $$PWD/ext/date/lib/parse_iso_intervals.c \
   $$PWD/ext/date/lib/parse_tz.c \
   $$PWD/ext/date/lib/timelib.c \
   $$PWD/ext/date/lib/tm2unixtime.c \
   $$PWD/ext/date/lib/unixtime2tm.c \
   $$PWD/ext/date/php_date.c \
   $$PWD/ext/dba/libcdb/cdb.c \
   $$PWD/ext/dba/libcdb/cdb_make.c \
   $$PWD/ext/dba/libcdb/uint32.c \
   $$PWD/ext/dba/libflatfile/flatfile.c \
   $$PWD/ext/dba/libinifile/inifile.c \
   $$PWD/ext/dba/dba.c \
   $$PWD/ext/dba/dba_cdb.c \
   $$PWD/ext/dba/dba_db1.c \
   $$PWD/ext/dba/dba_db2.c \
   $$PWD/ext/dba/dba_db3.c \
   $$PWD/ext/dba/dba_db4.c \
   $$PWD/ext/dba/dba_dbm.c \
   $$PWD/ext/dba/dba_flatfile.c \
   $$PWD/ext/dba/dba_gdbm.c \
   $$PWD/ext/dba/dba_inifile.c \
   $$PWD/ext/dba/dba_lmdb.c \
   $$PWD/ext/dba/dba_ndbm.c \
   $$PWD/ext/dba/dba_qdbm.c \
   $$PWD/ext/dba/dba_tcadb.c \
   $$PWD/ext/dom/attr.c \
   $$PWD/ext/dom/cdatasection.c \
   $$PWD/ext/dom/characterdata.c \
   $$PWD/ext/dom/comment.c \
   $$PWD/ext/dom/document.c \
   $$PWD/ext/dom/documentfragment.c \
   $$PWD/ext/dom/documenttype.c \
   $$PWD/ext/dom/dom_iterators.c \
   $$PWD/ext/dom/domconfiguration.c \
   $$PWD/ext/dom/domerror.c \
   $$PWD/ext/dom/domerrorhandler.c \
   $$PWD/ext/dom/domexception.c \
   $$PWD/ext/dom/domimplementation.c \
   $$PWD/ext/dom/domimplementationlist.c \
   $$PWD/ext/dom/domimplementationsource.c \
   $$PWD/ext/dom/domlocator.c \
   $$PWD/ext/dom/domstringlist.c \
   $$PWD/ext/dom/element.c \
   $$PWD/ext/dom/entity.c \
   $$PWD/ext/dom/entityreference.c \
   $$PWD/ext/dom/namednodemap.c \
   $$PWD/ext/dom/namelist.c \
   $$PWD/ext/dom/node.c \
   $$PWD/ext/dom/nodelist.c \
   $$PWD/ext/dom/notation.c \
   $$PWD/ext/dom/php_dom.c \
   $$PWD/ext/dom/processinginstruction.c \
   $$PWD/ext/dom/string_extend.c \
   $$PWD/ext/dom/text.c \
   $$PWD/ext/dom/typeinfo.c \
   $$PWD/ext/dom/userdatahandler.c \
   $$PWD/ext/dom/xpath.c \
   $$PWD/ext/enchant/enchant.c \
   $$PWD/ext/exif/exif.c \
   $$PWD/ext/fileinfo/libmagic/apprentice.c \
   $$PWD/ext/fileinfo/libmagic/apptype.c \
   $$PWD/ext/fileinfo/libmagic/ascmagic.c \
   $$PWD/ext/fileinfo/libmagic/cdf.c \
   $$PWD/ext/fileinfo/libmagic/cdf_time.c \
   $$PWD/ext/fileinfo/libmagic/compress.c \
   $$PWD/ext/fileinfo/libmagic/der.c \
   $$PWD/ext/fileinfo/libmagic/encoding.c \
   $$PWD/ext/fileinfo/libmagic/fsmagic.c \
   $$PWD/ext/fileinfo/libmagic/funcs.c \
   $$PWD/ext/fileinfo/libmagic/is_tar.c \
   $$PWD/ext/fileinfo/libmagic/magic.c \
   $$PWD/ext/fileinfo/libmagic/print.c \
   $$PWD/ext/fileinfo/libmagic/readcdf.c \
   $$PWD/ext/fileinfo/libmagic/softmagic.c \
   $$PWD/ext/fileinfo/libmagic/strcasestr.c \
   $$PWD/ext/fileinfo/data_file.c \
   $$PWD/ext/fileinfo/fileinfo.c \
   $$PWD/ext/filter/callback_filter.c \
   $$PWD/ext/filter/filter.c \
   $$PWD/ext/filter/logical_filters.c \
   $$PWD/ext/filter/sanitizing_filters.c \
   $$PWD/ext/ftp/ftp.c \
   $$PWD/ext/ftp/php_ftp.c \
   $$PWD/ext/gd/libgd/gd.c \
   $$PWD/ext/gd/libgd/gd2copypal.c \
   $$PWD/ext/gd/libgd/gd2time.c \
   $$PWD/ext/gd/libgd/gd2topng.c \
   $$PWD/ext/gd/libgd/gd_bmp.c \
   $$PWD/ext/gd/libgd/gd_color_match.c \
   $$PWD/ext/gd/libgd/gd_crop.c \
   $$PWD/ext/gd/libgd/gd_filter.c \
   $$PWD/ext/gd/libgd/gd_gd.c \
   $$PWD/ext/gd/libgd/gd_gd2.c \
   $$PWD/ext/gd/libgd/gd_gif_in.c \
   $$PWD/ext/gd/libgd/gd_gif_out.c \
   $$PWD/ext/gd/libgd/gd_interpolation.c \
   $$PWD/ext/gd/libgd/gd_io.c \
   $$PWD/ext/gd/libgd/gd_io_dp.c \
   $$PWD/ext/gd/libgd/gd_io_file.c \
   $$PWD/ext/gd/libgd/gd_io_ss.c \
   $$PWD/ext/gd/libgd/gd_jpeg.c \
   $$PWD/ext/gd/libgd/gd_matrix.c \
   $$PWD/ext/gd/libgd/gd_pixelate.c \
   $$PWD/ext/gd/libgd/gd_png.c \
   $$PWD/ext/gd/libgd/gd_rotate.c \
   $$PWD/ext/gd/libgd/gd_security.c \
   $$PWD/ext/gd/libgd/gd_ss.c \
   $$PWD/ext/gd/libgd/gd_topal.c \
   $$PWD/ext/gd/libgd/gd_transform.c \
   $$PWD/ext/gd/libgd/gd_wbmp.c \
   $$PWD/ext/gd/libgd/gd_webp.c \
   $$PWD/ext/gd/libgd/gd_xbm.c \
   $$PWD/ext/gd/libgd/gdcache.c \
   $$PWD/ext/gd/libgd/gddemo.c \
   $$PWD/ext/gd/libgd/gdfontg.c \
   $$PWD/ext/gd/libgd/gdfontl.c \
   $$PWD/ext/gd/libgd/gdfontmb.c \
   $$PWD/ext/gd/libgd/gdfonts.c \
   $$PWD/ext/gd/libgd/gdfontt.c \
   $$PWD/ext/gd/libgd/gdft.c \
   $$PWD/ext/gd/libgd/gdhelpers.c \
   $$PWD/ext/gd/libgd/gdkanji.c \
   $$PWD/ext/gd/libgd/gdparttopng.c \
   $$PWD/ext/gd/libgd/gdtables.c \
   $$PWD/ext/gd/libgd/gdtest.c \
   $$PWD/ext/gd/libgd/gdtestft.c \
   $$PWD/ext/gd/libgd/gdtopng.c \
   $$PWD/ext/gd/libgd/gdxpm.c \
   $$PWD/ext/gd/libgd/pngtogd.c \
   $$PWD/ext/gd/libgd/pngtogd2.c \
   $$PWD/ext/gd/libgd/testac.c \
   $$PWD/ext/gd/libgd/wbmp.c \
   $$PWD/ext/gd/libgd/webpng.c \
   $$PWD/ext/gd/gd.c \
   $$PWD/ext/gd/gd_compat.c \
   $$PWD/ext/gd/gd_ctx.c \
   $$PWD/ext/gd/gdcache.c \
   $$PWD/ext/gettext/gettext.c \
   $$PWD/ext/gmp/gmp.c \
   $$PWD/ext/hash/sha3/generic32lc/KeccakHash.c \
   $$PWD/ext/hash/sha3/generic32lc/KeccakP-1600-inplace32BI.c \
   $$PWD/ext/hash/sha3/generic32lc/KeccakSponge.c \
   $$PWD/ext/hash/sha3/generic64lc/KeccakHash.c \
   $$PWD/ext/hash/sha3/generic64lc/KeccakP-1600-opt64.c \
   $$PWD/ext/hash/sha3/generic64lc/KeccakSponge.c \
   $$PWD/ext/hash/hash.c \
   $$PWD/ext/hash/hash_adler32.c \
   $$PWD/ext/hash/hash_crc32.c \
   $$PWD/ext/hash/hash_fnv.c \
   $$PWD/ext/hash/hash_gost.c \
   $$PWD/ext/hash/hash_haval.c \
   $$PWD/ext/hash/hash_joaat.c \
   $$PWD/ext/hash/hash_md.c \
   $$PWD/ext/hash/hash_ripemd.c \
   $$PWD/ext/hash/hash_sha.c \
   $$PWD/ext/hash/hash_sha3.c \
   $$PWD/ext/hash/hash_snefru.c \
   $$PWD/ext/hash/hash_tiger.c \
   $$PWD/ext/hash/hash_whirlpool.c \
   $$PWD/ext/iconv/iconv.c \
   $$PWD/ext/imap/php_imap.c \
   $$PWD/ext/interbase/ibase_blobs.c \
   $$PWD/ext/interbase/ibase_events.c \
   $$PWD/ext/interbase/ibase_query.c \
   $$PWD/ext/interbase/ibase_service.c \
   $$PWD/ext/interbase/interbase.c \
   $$PWD/ext/interbase/php_ibase_udf.c \
   $$PWD/ext/intl/breakiterator/breakiterator_class.cpp \
   $$PWD/ext/intl/breakiterator/breakiterator_iterators.cpp \
   $$PWD/ext/intl/breakiterator/breakiterator_methods.cpp \
   $$PWD/ext/intl/breakiterator/codepointiterator_internal.cpp \
   $$PWD/ext/intl/breakiterator/codepointiterator_methods.cpp \
   $$PWD/ext/intl/breakiterator/rulebasedbreakiterator_methods.cpp \
   $$PWD/ext/intl/calendar/calendar_class.cpp \
   $$PWD/ext/intl/calendar/calendar_methods.cpp \
   $$PWD/ext/intl/calendar/gregoriancalendar_methods.cpp \
   $$PWD/ext/intl/collator/collator.c \
   $$PWD/ext/intl/collator/collator_attr.c \
   $$PWD/ext/intl/collator/collator_class.c \
   $$PWD/ext/intl/collator/collator_compare.c \
   $$PWD/ext/intl/collator/collator_convert.c \
   $$PWD/ext/intl/collator/collator_create.c \
   $$PWD/ext/intl/collator/collator_error.c \
   $$PWD/ext/intl/collator/collator_is_numeric.c \
   $$PWD/ext/intl/collator/collator_locale.c \
   $$PWD/ext/intl/collator/collator_sort.c \
   $$PWD/ext/intl/common/common_date.cpp \
   $$PWD/ext/intl/common/common_enum.cpp \
   $$PWD/ext/intl/common/common_error.c \
   $$PWD/ext/intl/converter/converter.c \
   $$PWD/ext/intl/dateformat/dateformat.c \
   $$PWD/ext/intl/dateformat/dateformat_attr.c \
   $$PWD/ext/intl/dateformat/dateformat_attrcpp.cpp \
   $$PWD/ext/intl/dateformat/dateformat_class.c \
   $$PWD/ext/intl/dateformat/dateformat_create.cpp \
   $$PWD/ext/intl/dateformat/dateformat_data.c \
   $$PWD/ext/intl/dateformat/dateformat_format.c \
   $$PWD/ext/intl/dateformat/dateformat_format_object.cpp \
   $$PWD/ext/intl/dateformat/dateformat_helpers.cpp \
   $$PWD/ext/intl/dateformat/dateformat_parse.c \
   $$PWD/ext/intl/formatter/formatter.c \
   $$PWD/ext/intl/formatter/formatter_attr.c \
   $$PWD/ext/intl/formatter/formatter_class.c \
   $$PWD/ext/intl/formatter/formatter_data.c \
   $$PWD/ext/intl/formatter/formatter_format.c \
   $$PWD/ext/intl/formatter/formatter_main.c \
   $$PWD/ext/intl/formatter/formatter_parse.c \
   $$PWD/ext/intl/grapheme/grapheme_string.c \
   $$PWD/ext/intl/grapheme/grapheme_util.c \
   $$PWD/ext/intl/idn/idn.c \
   $$PWD/ext/intl/locale/locale.c \
   $$PWD/ext/intl/locale/locale_class.c \
   $$PWD/ext/intl/locale/locale_methods.c \
   $$PWD/ext/intl/msgformat/msgformat.c \
   $$PWD/ext/intl/msgformat/msgformat_attr.c \
   $$PWD/ext/intl/msgformat/msgformat_class.c \
   $$PWD/ext/intl/msgformat/msgformat_data.c \
   $$PWD/ext/intl/msgformat/msgformat_format.c \
   $$PWD/ext/intl/msgformat/msgformat_helpers.cpp \
   $$PWD/ext/intl/msgformat/msgformat_parse.c \
   $$PWD/ext/intl/normalizer/normalizer.c \
   $$PWD/ext/intl/normalizer/normalizer_class.c \
   $$PWD/ext/intl/normalizer/normalizer_normalize.c \
   $$PWD/ext/intl/resourcebundle/resourcebundle.c \
   $$PWD/ext/intl/resourcebundle/resourcebundle_class.c \
   $$PWD/ext/intl/resourcebundle/resourcebundle_iterator.c \
   $$PWD/ext/intl/spoofchecker/spoofchecker.c \
   $$PWD/ext/intl/spoofchecker/spoofchecker_class.c \
   $$PWD/ext/intl/spoofchecker/spoofchecker_create.c \
   $$PWD/ext/intl/spoofchecker/spoofchecker_main.c \
   $$PWD/ext/intl/timezone/timezone_class.cpp \
   $$PWD/ext/intl/timezone/timezone_methods.cpp \
   $$PWD/ext/intl/transliterator/transliterator.c \
   $$PWD/ext/intl/transliterator/transliterator_class.c \
   $$PWD/ext/intl/transliterator/transliterator_methods.c \
   $$PWD/ext/intl/uchar/uchar.c \
   $$PWD/ext/intl/intl_convert.c \
   $$PWD/ext/intl/intl_convertcpp.cpp \
   $$PWD/ext/intl/intl_error.c \
   $$PWD/ext/intl/php_intl.c \
   $$PWD/ext/json/json.c \
   $$PWD/ext/json/json_encoder.c \
   $$PWD/ext/json/json_parser.tab.c \
   $$PWD/ext/json/json_scanner.c \
   $$PWD/ext/ldap/ldap.c \
   $$PWD/ext/libxml/libxml.c \
   $$PWD/ext/mbstring/libmbfl/filters/html_entities.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_7bit.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_armscii8.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_ascii.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_base64.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_big5.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_byte2.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_byte4.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp1251.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp1252.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp1254.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp5022x.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp51932.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp850.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp866.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp932.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_cp936.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_euc_cn.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_euc_jp.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_euc_jp_2004.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_euc_jp_win.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_euc_kr.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_euc_tw.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_gb18030.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_htmlent.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_hz.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso2022_jp_ms.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso2022_kr.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso2022jp_2004.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso2022jp_mobile.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_1.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_10.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_13.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_14.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_15.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_16.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_2.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_3.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_4.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_5.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_6.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_7.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_8.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_iso8859_9.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_jis.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_koi8r.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_koi8u.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_qprint.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_sjis.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_sjis_2004.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_sjis_mac.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_sjis_mobile.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_sjis_open.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_tl_jisx0201_jisx0208.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_ucs2.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_ucs4.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_uhc.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_utf16.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_utf32.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_utf7.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_utf7imap.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_utf8.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_utf8_mobile.c \
   $$PWD/ext/mbstring/libmbfl/filters/mbfilter_uuencode.c \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfilter.c \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfilter_8bit.c \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfilter_pass.c \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfilter_wchar.c \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_allocators.c \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_convert.c \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_encoding.c \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_filter_output.c \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_ident.c \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_language.c \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_memory_device.c \
   $$PWD/ext/mbstring/libmbfl/mbfl/mbfl_string.c \
   $$PWD/ext/mbstring/libmbfl/nls/nls_de.c \
   $$PWD/ext/mbstring/libmbfl/nls/nls_en.c \
   $$PWD/ext/mbstring/libmbfl/nls/nls_hy.c \
   $$PWD/ext/mbstring/libmbfl/nls/nls_ja.c \
   $$PWD/ext/mbstring/libmbfl/nls/nls_kr.c \
   $$PWD/ext/mbstring/libmbfl/nls/nls_neutral.c \
   $$PWD/ext/mbstring/libmbfl/nls/nls_ru.c \
   $$PWD/ext/mbstring/libmbfl/nls/nls_tr.c \
   $$PWD/ext/mbstring/libmbfl/nls/nls_ua.c \
   $$PWD/ext/mbstring/libmbfl/nls/nls_uni.c \
   $$PWD/ext/mbstring/libmbfl/nls/nls_zh.c \
   $$PWD/ext/mbstring/libmbfl/tests/conv_encoding.tests/gen_exp.c \
   $$PWD/ext/mbstring/libmbfl/tests/conv_encoding.c \
   $$PWD/ext/mbstring/libmbfl/tests/conv_kana.c \
   $$PWD/ext/mbstring/libmbfl/tests/emoji.c \
   $$PWD/ext/mbstring/libmbfl/tests/sample.c \
   $$PWD/ext/mbstring/libmbfl/tests/strcut.c \
   $$PWD/ext/mbstring/libmbfl/tests/strwidth.c \
   $$PWD/ext/mbstring/oniguruma/src/ascii.c \
   $$PWD/ext/mbstring/oniguruma/src/big5.c \
   $$PWD/ext/mbstring/oniguruma/src/cp1251.c \
   $$PWD/ext/mbstring/oniguruma/src/euc_jp.c \
   $$PWD/ext/mbstring/oniguruma/src/euc_jp_prop.c \
   $$PWD/ext/mbstring/oniguruma/src/euc_kr.c \
   $$PWD/ext/mbstring/oniguruma/src/euc_tw.c \
   $$PWD/ext/mbstring/oniguruma/src/gb18030.c \
   $$PWD/ext/mbstring/oniguruma/src/iso8859_1.c \
   $$PWD/ext/mbstring/oniguruma/src/iso8859_10.c \
   $$PWD/ext/mbstring/oniguruma/src/iso8859_11.c \
   $$PWD/ext/mbstring/oniguruma/src/iso8859_13.c \
   $$PWD/ext/mbstring/oniguruma/src/iso8859_14.c \
   $$PWD/ext/mbstring/oniguruma/src/iso8859_15.c \
   $$PWD/ext/mbstring/oniguruma/src/iso8859_16.c \
   $$PWD/ext/mbstring/oniguruma/src/iso8859_2.c \
   $$PWD/ext/mbstring/oniguruma/src/iso8859_3.c \
   $$PWD/ext/mbstring/oniguruma/src/iso8859_4.c \
   $$PWD/ext/mbstring/oniguruma/src/iso8859_5.c \
   $$PWD/ext/mbstring/oniguruma/src/iso8859_6.c \
   $$PWD/ext/mbstring/oniguruma/src/iso8859_7.c \
   $$PWD/ext/mbstring/oniguruma/src/iso8859_8.c \
   $$PWD/ext/mbstring/oniguruma/src/iso8859_9.c \
   $$PWD/ext/mbstring/oniguruma/src/koi8.c \
   $$PWD/ext/mbstring/oniguruma/src/koi8_r.c \
   $$PWD/ext/mbstring/oniguruma/src/mktable.c \
   $$PWD/ext/mbstring/oniguruma/src/onig_init.c \
   $$PWD/ext/mbstring/oniguruma/src/regcomp.c \
   $$PWD/ext/mbstring/oniguruma/src/regenc.c \
   $$PWD/ext/mbstring/oniguruma/src/regerror.c \
   $$PWD/ext/mbstring/oniguruma/src/regexec.c \
   $$PWD/ext/mbstring/oniguruma/src/regext.c \
   $$PWD/ext/mbstring/oniguruma/src/reggnu.c \
   $$PWD/ext/mbstring/oniguruma/src/regparse.c \
   $$PWD/ext/mbstring/oniguruma/src/regposerr.c \
   $$PWD/ext/mbstring/oniguruma/src/regposix.c \
   $$PWD/ext/mbstring/oniguruma/src/regsyntax.c \
   $$PWD/ext/mbstring/oniguruma/src/regtrav.c \
   $$PWD/ext/mbstring/oniguruma/src/regversion.c \
   $$PWD/ext/mbstring/oniguruma/src/sjis.c \
   $$PWD/ext/mbstring/oniguruma/src/sjis_prop.c \
   $$PWD/ext/mbstring/oniguruma/src/st.c \
   $$PWD/ext/mbstring/oniguruma/src/unicode.c \
   $$PWD/ext/mbstring/oniguruma/src/unicode_fold1_key.c \
   $$PWD/ext/mbstring/oniguruma/src/unicode_fold2_key.c \
   $$PWD/ext/mbstring/oniguruma/src/unicode_fold3_key.c \
   $$PWD/ext/mbstring/oniguruma/src/unicode_fold_data.c \
   $$PWD/ext/mbstring/oniguruma/src/unicode_property_data.c \
   $$PWD/ext/mbstring/oniguruma/src/unicode_property_data_posix.c \
   $$PWD/ext/mbstring/oniguruma/src/unicode_unfold_key.c \
   $$PWD/ext/mbstring/oniguruma/src/utf16_be.c \
   $$PWD/ext/mbstring/oniguruma/src/utf16_le.c \
   $$PWD/ext/mbstring/oniguruma/src/utf32_be.c \
   $$PWD/ext/mbstring/oniguruma/src/utf32_le.c \
   $$PWD/ext/mbstring/oniguruma/src/utf8.c \
   $$PWD/ext/mbstring/ucgendat/ucgendat.c \
   $$PWD/ext/mbstring/mb_gpc.c \
   $$PWD/ext/mbstring/mbstring.c \
   $$PWD/ext/mbstring/php_mbregex.c \
   $$PWD/ext/mbstring/php_unicode.c \
   $$PWD/ext/mysqli/mysqli.c \
   $$PWD/ext/mysqli/mysqli_api.c \
   $$PWD/ext/mysqli/mysqli_driver.c \
   $$PWD/ext/mysqli/mysqli_embedded.c \
   $$PWD/ext/mysqli/mysqli_exception.c \
   $$PWD/ext/mysqli/mysqli_fe.c \
   $$PWD/ext/mysqli/mysqli_nonapi.c \
   $$PWD/ext/mysqli/mysqli_prop.c \
   $$PWD/ext/mysqli/mysqli_report.c \
   $$PWD/ext/mysqli/mysqli_result_iterator.c \
   $$PWD/ext/mysqli/mysqli_warning.c \
   $$PWD/ext/mysqlnd/mysqlnd_alloc.c \
   $$PWD/ext/mysqlnd/mysqlnd_auth.c \
   $$PWD/ext/mysqlnd/mysqlnd_block_alloc.c \
   $$PWD/ext/mysqlnd/mysqlnd_charset.c \
   $$PWD/ext/mysqlnd/mysqlnd_commands.c \
   $$PWD/ext/mysqlnd/mysqlnd_connection.c \
   $$PWD/ext/mysqlnd/mysqlnd_debug.c \
   $$PWD/ext/mysqlnd/mysqlnd_driver.c \
   $$PWD/ext/mysqlnd/mysqlnd_ext_plugin.c \
   $$PWD/ext/mysqlnd/mysqlnd_loaddata.c \
   $$PWD/ext/mysqlnd/mysqlnd_net.c \
   $$PWD/ext/mysqlnd/mysqlnd_plugin.c \
   $$PWD/ext/mysqlnd/mysqlnd_protocol_frame_codec.c \
   $$PWD/ext/mysqlnd/mysqlnd_ps.c \
   $$PWD/ext/mysqlnd/mysqlnd_ps_codec.c \
   $$PWD/ext/mysqlnd/mysqlnd_read_buffer.c \
   $$PWD/ext/mysqlnd/mysqlnd_result.c \
   $$PWD/ext/mysqlnd/mysqlnd_result_meta.c \
   $$PWD/ext/mysqlnd/mysqlnd_reverse_api.c \
   $$PWD/ext/mysqlnd/mysqlnd_statistics.c \
   $$PWD/ext/mysqlnd/mysqlnd_vio.c \
   $$PWD/ext/mysqlnd/mysqlnd_wireprotocol.c \
   $$PWD/ext/mysqlnd/php_mysqlnd.c \
   $$PWD/ext/oci8/oci8.c \
   $$PWD/ext/oci8/oci8_collection.c \
   $$PWD/ext/oci8/oci8_failover.c \
   $$PWD/ext/oci8/oci8_interface.c \
   $$PWD/ext/oci8/oci8_lob.c \
   $$PWD/ext/oci8/oci8_statement.c \
   $$PWD/ext/odbc/birdstep.c \
   $$PWD/ext/odbc/php_odbc.c \
   $$PWD/ext/opcache/Optimizer/block_pass.c \
   $$PWD/ext/opcache/Optimizer/compact_literals.c \
   $$PWD/ext/opcache/Optimizer/compact_vars.c \
   $$PWD/ext/opcache/Optimizer/dce.c \
   $$PWD/ext/opcache/Optimizer/dfa_pass.c \
   $$PWD/ext/opcache/Optimizer/nop_removal.c \
   $$PWD/ext/opcache/Optimizer/optimize_func_calls.c \
   $$PWD/ext/opcache/Optimizer/optimize_temp_vars_5.c \
   $$PWD/ext/opcache/Optimizer/pass1_5.c \
   $$PWD/ext/opcache/Optimizer/pass2.c \
   $$PWD/ext/opcache/Optimizer/pass3.c \
   $$PWD/ext/opcache/Optimizer/sccp.c \
   $$PWD/ext/opcache/Optimizer/scdf.c \
   $$PWD/ext/opcache/Optimizer/ssa_integrity.c \
   $$PWD/ext/opcache/Optimizer/zend_call_graph.c \
   $$PWD/ext/opcache/Optimizer/zend_cfg.c \
   $$PWD/ext/opcache/Optimizer/zend_dfg.c \
   $$PWD/ext/opcache/Optimizer/zend_dump.c \
   $$PWD/ext/opcache/Optimizer/zend_func_info.c \
   $$PWD/ext/opcache/Optimizer/zend_inference.c \
   $$PWD/ext/opcache/Optimizer/zend_optimizer.c \
   $$PWD/ext/opcache/Optimizer/zend_ssa.c \
   $$PWD/ext/opcache/shared_alloc_mmap.c \
   $$PWD/ext/opcache/shared_alloc_posix.c \
   $$PWD/ext/opcache/shared_alloc_shm.c \
   $$PWD/ext/opcache/shared_alloc_win32.c \
   $$PWD/ext/opcache/zend_accelerator_blacklist.c \
   $$PWD/ext/opcache/zend_accelerator_debug.c \
   $$PWD/ext/opcache/zend_accelerator_hash.c \
   $$PWD/ext/opcache/zend_accelerator_module.c \
   $$PWD/ext/opcache/zend_accelerator_util_funcs.c \
   $$PWD/ext/opcache/zend_file_cache.c \
   $$PWD/ext/opcache/zend_persist.c \
   $$PWD/ext/opcache/zend_persist_calc.c \
   $$PWD/ext/opcache/zend_shared_alloc.c \
   $$PWD/ext/opcache/ZendAccelerator.c \
   $$PWD/ext/openssl/openssl.c \
   $$PWD/ext/openssl/xp_ssl.c \
   $$PWD/ext/pcntl/pcntl.c \
   $$PWD/ext/pcntl/php_signal.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitExecAllocator.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitLir.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativeARM_32.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativeARM_64.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativeARM_T2_32.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativeMIPS_32.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativeMIPS_64.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativeMIPS_common.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativePPC_32.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativePPC_64.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativePPC_common.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativeSPARC_32.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativeSPARC_common.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativeTILEGX-encoder.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativeTILEGX_64.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativeX86_32.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativeX86_64.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitNativeX86_common.c \
   $$PWD/ext/pcre/pcrelib/sljit/sljitUtils.c \
   $$PWD/ext/pcre/pcrelib/dftables.c \
   $$PWD/ext/pcre/pcrelib/pcre_chartables.c \
   $$PWD/ext/pcre/pcrelib/pcre_compile.c \
   $$PWD/ext/pcre/pcrelib/pcre_config.c \
   $$PWD/ext/pcre/pcrelib/pcre_exec.c \
   $$PWD/ext/pcre/pcrelib/pcre_fullinfo.c \
   $$PWD/ext/pcre/pcrelib/pcre_get.c \
   $$PWD/ext/pcre/pcrelib/pcre_globals.c \
   $$PWD/ext/pcre/pcrelib/pcre_jit_compile.c \
   $$PWD/ext/pcre/pcrelib/pcre_maketables.c \
   $$PWD/ext/pcre/pcrelib/pcre_newline.c \
   $$PWD/ext/pcre/pcrelib/pcre_ord2utf8.c \
   $$PWD/ext/pcre/pcrelib/pcre_printint.c \
   $$PWD/ext/pcre/pcrelib/pcre_refcount.c \
   $$PWD/ext/pcre/pcrelib/pcre_study.c \
   $$PWD/ext/pcre/pcrelib/pcre_tables.c \
   $$PWD/ext/pcre/pcrelib/pcre_ucd.c \
   $$PWD/ext/pcre/pcrelib/pcre_valid_utf8.c \
   $$PWD/ext/pcre/pcrelib/pcre_version.c \
   $$PWD/ext/pcre/pcrelib/pcre_xclass.c \
   $$PWD/ext/pcre/pcrelib/pcredemo.c \
   $$PWD/ext/pcre/pcrelib/pcreposix.c \
   $$PWD/ext/pcre/php_pcre.c \
   $$PWD/ext/pdo/pdo.c \
   $$PWD/ext/pdo/pdo_dbh.c \
   $$PWD/ext/pdo/pdo_sql_parser.c \
   $$PWD/ext/pdo/pdo_sqlstate.c \
   $$PWD/ext/pdo/pdo_stmt.c \
   $$PWD/ext/pdo_dblib/dblib_driver.c \
   $$PWD/ext/pdo_dblib/dblib_stmt.c \
   $$PWD/ext/pdo_dblib/pdo_dblib.c \
   $$PWD/ext/pdo_firebird/firebird_driver.c \
   $$PWD/ext/pdo_firebird/firebird_statement.c \
   $$PWD/ext/pdo_firebird/pdo_firebird.c \
   $$PWD/ext/pdo_mysql/mysql_driver.c \
   $$PWD/ext/pdo_mysql/mysql_statement.c \
   $$PWD/ext/pdo_mysql/pdo_mysql.c \
   $$PWD/ext/pdo_oci/oci_driver.c \
   $$PWD/ext/pdo_oci/oci_statement.c \
   $$PWD/ext/pdo_oci/pdo_oci.c \
   $$PWD/ext/pdo_odbc/odbc_driver.c \
   $$PWD/ext/pdo_odbc/odbc_stmt.c \
   $$PWD/ext/pdo_odbc/pdo_odbc.c \
   $$PWD/ext/pdo_pgsql/pdo_pgsql.c \
   $$PWD/ext/pdo_pgsql/pgsql_driver.c \
   $$PWD/ext/pdo_pgsql/pgsql_statement.c \
   $$PWD/ext/pdo_sqlite/pdo_sqlite.c \
   $$PWD/ext/pdo_sqlite/sqlite_driver.c \
   $$PWD/ext/pdo_sqlite/sqlite_statement.c \
   $$PWD/ext/pgsql/pgsql.c \
   $$PWD/ext/phar/dirstream.c \
   $$PWD/ext/phar/func_interceptors.c \
   $$PWD/ext/phar/phar.c \
   $$PWD/ext/phar/phar_object.c \
   $$PWD/ext/phar/phar_path_check.c \
   $$PWD/ext/phar/stream.c \
   $$PWD/ext/phar/tar.c \
   $$PWD/ext/phar/util.c \
   $$PWD/ext/phar/zip.c \
   $$PWD/ext/posix/posix.c \
   $$PWD/ext/pspell/pspell.c \
   $$PWD/ext/readline/readline.c \
   $$PWD/ext/readline/readline_cli.c \
   $$PWD/ext/recode/recode.c \
   $$PWD/ext/reflection/php_reflection.c \
   $$PWD/ext/session/mod_files.c \
   $$PWD/ext/session/mod_mm.c \
   $$PWD/ext/session/mod_user.c \
   $$PWD/ext/session/mod_user_class.c \
   $$PWD/ext/session/session.c \
   $$PWD/ext/shmop/shmop.c \
   $$PWD/ext/simplexml/simplexml.c \
   $$PWD/ext/simplexml/sxe.c \
   $$PWD/ext/skeleton/skeleton.c \
   $$PWD/ext/snmp/snmp.c \
   $$PWD/ext/soap/php_encoding.c \
   $$PWD/ext/soap/php_http.c \
   $$PWD/ext/soap/php_packet_soap.c \
   $$PWD/ext/soap/php_schema.c \
   $$PWD/ext/soap/php_sdl.c \
   $$PWD/ext/soap/php_xml.c \
   $$PWD/ext/soap/soap.c \
   $$PWD/ext/sockets/conversions.c \
   $$PWD/ext/sockets/multicast.c \
   $$PWD/ext/sockets/sendrecvmsg.c \
   $$PWD/ext/sockets/sockaddr_conv.c \
   $$PWD/ext/sockets/sockets.c \
   $$PWD/ext/sodium/libsodium.c \
   $$PWD/ext/spl/php_spl.c \
   $$PWD/ext/spl/spl_array.c \
   $$PWD/ext/spl/spl_directory.c \
   $$PWD/ext/spl/spl_dllist.c \
   $$PWD/ext/spl/spl_engine.c \
   $$PWD/ext/spl/spl_exceptions.c \
   $$PWD/ext/spl/spl_fixedarray.c \
   $$PWD/ext/spl/spl_functions.c \
   $$PWD/ext/spl/spl_heap.c \
   $$PWD/ext/spl/spl_iterators.c \
   $$PWD/ext/spl/spl_observer.c \
   $$PWD/ext/sqlite3/libsqlite/sqlite3.c \
   $$PWD/ext/sqlite3/sqlite3.c \
   $$PWD/ext/standard/array.c \
   $$PWD/ext/standard/assert.c \
   $$PWD/ext/standard/base64.c \
   $$PWD/ext/standard/basic_functions.c \
   $$PWD/ext/standard/browscap.c \
   $$PWD/ext/standard/crc32.c \
   $$PWD/ext/standard/credits.c \
   $$PWD/ext/standard/crypt.c \
   $$PWD/ext/standard/crypt_blowfish.c \
   $$PWD/ext/standard/crypt_freesec.c \
   $$PWD/ext/standard/crypt_sha256.c \
   $$PWD/ext/standard/crypt_sha512.c \
   $$PWD/ext/standard/css.c \
   $$PWD/ext/standard/cyr_convert.c \
   $$PWD/ext/standard/datetime.c \
   $$PWD/ext/standard/dir.c \
   $$PWD/ext/standard/dl.c \
   $$PWD/ext/standard/dns.c \
   $$PWD/ext/standard/dns_win32.c \
   $$PWD/ext/standard/exec.c \
   $$PWD/ext/standard/file.c \
   $$PWD/ext/standard/filestat.c \
   $$PWD/ext/standard/filters.c \
   $$PWD/ext/standard/flock_compat.c \
   $$PWD/ext/standard/formatted_print.c \
   $$PWD/ext/standard/fsock.c \
   $$PWD/ext/standard/ftok.c \
   $$PWD/ext/standard/ftp_fopen_wrapper.c \
   $$PWD/ext/standard/head.c \
   $$PWD/ext/standard/html.c \
   $$PWD/ext/standard/http.c \
   $$PWD/ext/standard/http_fopen_wrapper.c \
   $$PWD/ext/standard/image.c \
   $$PWD/ext/standard/incomplete_class.c \
   $$PWD/ext/standard/info.c \
   $$PWD/ext/standard/iptc.c \
   $$PWD/ext/standard/lcg.c \
   $$PWD/ext/standard/levenshtein.c \
   $$PWD/ext/standard/link.c \
   $$PWD/ext/standard/link_win32.c \
   $$PWD/ext/standard/mail.c \
   $$PWD/ext/standard/math.c \
   $$PWD/ext/standard/md5.c \
   $$PWD/ext/standard/metaphone.c \
   $$PWD/ext/standard/microtime.c \
   $$PWD/ext/standard/mt_rand.c \
   $$PWD/ext/standard/pack.c \
   $$PWD/ext/standard/pageinfo.c \
   $$PWD/ext/standard/password.c \
   $$PWD/ext/standard/php_crypt_r.c \
   $$PWD/ext/standard/php_fopen_wrapper.c \
   $$PWD/ext/standard/proc_open.c \
   $$PWD/ext/standard/quot_print.c \
   $$PWD/ext/standard/rand.c \
   $$PWD/ext/standard/random.c \
   $$PWD/ext/standard/scanf.c \
   $$PWD/ext/standard/sha1.c \
   $$PWD/ext/standard/soundex.c \
   $$PWD/ext/standard/streamsfuncs.c \
   $$PWD/ext/standard/string.c \
   $$PWD/ext/standard/strnatcmp.c \
   $$PWD/ext/standard/syslog.c \
   $$PWD/ext/standard/type.c \
   $$PWD/ext/standard/uniqid.c \
   $$PWD/ext/standard/url.c \
   $$PWD/ext/standard/url_scanner_ex.c \
   $$PWD/ext/standard/user_filters.c \
   $$PWD/ext/standard/uuencode.c \
   $$PWD/ext/standard/var.c \
   $$PWD/ext/standard/var_unserializer.c \
   $$PWD/ext/standard/versioning.c \
   $$PWD/ext/sysvmsg/sysvmsg.c \
   $$PWD/ext/sysvsem/sysvsem.c \
   $$PWD/ext/sysvshm/sysvshm.c \
   $$PWD/ext/tidy/tidy.c \
   $$PWD/ext/tokenizer/tokenizer.c \
   $$PWD/ext/tokenizer/tokenizer_data.c \
   $$PWD/ext/wddx/wddx.c \
   $$PWD/ext/xml/compat.c \
   $$PWD/ext/xml/xml.c \
   $$PWD/ext/xmlreader/php_xmlreader.c \
   $$PWD/ext/xmlrpc/libxmlrpc/base64.c \
   $$PWD/ext/xmlrpc/libxmlrpc/encodings.c \
   $$PWD/ext/xmlrpc/libxmlrpc/queue.c \
   $$PWD/ext/xmlrpc/libxmlrpc/simplestring.c \
   $$PWD/ext/xmlrpc/libxmlrpc/system_methods.c \
   $$PWD/ext/xmlrpc/libxmlrpc/xml_element.c \
   $$PWD/ext/xmlrpc/libxmlrpc/xml_to_dandarpc.c \
   $$PWD/ext/xmlrpc/libxmlrpc/xml_to_soap.c \
   $$PWD/ext/xmlrpc/libxmlrpc/xml_to_xmlrpc.c \
   $$PWD/ext/xmlrpc/libxmlrpc/xmlrpc.c \
   $$PWD/ext/xmlrpc/libxmlrpc/xmlrpc_introspection.c \
   $$PWD/ext/xmlrpc/xmlrpc-epi-php.c \
   $$PWD/ext/xmlwriter/php_xmlwriter.c \
   $$PWD/ext/xsl/php_xsl.c \
   $$PWD/ext/xsl/xsltprocessor.c \
   $$PWD/ext/zend_test/test.c \
   $$PWD/ext/zip/lib/mkstemp.c \
   $$PWD/ext/zip/lib/zip_add.c \
   $$PWD/ext/zip/lib/zip_add_dir.c \
   $$PWD/ext/zip/lib/zip_add_entry.c \
   $$PWD/ext/zip/lib/zip_buffer.c \
   $$PWD/ext/zip/lib/zip_close.c \
   $$PWD/ext/zip/lib/zip_delete.c \
   $$PWD/ext/zip/lib/zip_dir_add.c \
   $$PWD/ext/zip/lib/zip_dirent.c \
   $$PWD/ext/zip/lib/zip_discard.c \
   $$PWD/ext/zip/lib/zip_entry.c \
   $$PWD/ext/zip/lib/zip_err_str.c \
   $$PWD/ext/zip/lib/zip_error.c \
   $$PWD/ext/zip/lib/zip_error_clear.c \
   $$PWD/ext/zip/lib/zip_error_get.c \
   $$PWD/ext/zip/lib/zip_error_get_sys_type.c \
   $$PWD/ext/zip/lib/zip_error_strerror.c \
   $$PWD/ext/zip/lib/zip_error_to_str.c \
   $$PWD/ext/zip/lib/zip_extra_field.c \
   $$PWD/ext/zip/lib/zip_extra_field_api.c \
   $$PWD/ext/zip/lib/zip_fclose.c \
   $$PWD/ext/zip/lib/zip_fdopen.c \
   $$PWD/ext/zip/lib/zip_file_add.c \
   $$PWD/ext/zip/lib/zip_file_error_clear.c \
   $$PWD/ext/zip/lib/zip_file_error_get.c \
   $$PWD/ext/zip/lib/zip_file_get_comment.c \
   $$PWD/ext/zip/lib/zip_file_get_external_attributes.c \
   $$PWD/ext/zip/lib/zip_file_get_offset.c \
   $$PWD/ext/zip/lib/zip_file_rename.c \
   $$PWD/ext/zip/lib/zip_file_replace.c \
   $$PWD/ext/zip/lib/zip_file_set_comment.c \
   $$PWD/ext/zip/lib/zip_file_set_external_attributes.c \
   $$PWD/ext/zip/lib/zip_file_set_mtime.c \
   $$PWD/ext/zip/lib/zip_file_strerror.c \
   $$PWD/ext/zip/lib/zip_filerange_crc.c \
   $$PWD/ext/zip/lib/zip_fopen.c \
   $$PWD/ext/zip/lib/zip_fopen_encrypted.c \
   $$PWD/ext/zip/lib/zip_fopen_index.c \
   $$PWD/ext/zip/lib/zip_fopen_index_encrypted.c \
   $$PWD/ext/zip/lib/zip_fread.c \
   $$PWD/ext/zip/lib/zip_get_archive_comment.c \
   $$PWD/ext/zip/lib/zip_get_archive_flag.c \
   $$PWD/ext/zip/lib/zip_get_compression_implementation.c \
   $$PWD/ext/zip/lib/zip_get_encryption_implementation.c \
   $$PWD/ext/zip/lib/zip_get_file_comment.c \
   $$PWD/ext/zip/lib/zip_get_name.c \
   $$PWD/ext/zip/lib/zip_get_num_entries.c \
   $$PWD/ext/zip/lib/zip_get_num_files.c \
   $$PWD/ext/zip/lib/zip_hash.c \
   $$PWD/ext/zip/lib/zip_io_util.c \
   $$PWD/ext/zip/lib/zip_memdup.c \
   $$PWD/ext/zip/lib/zip_name_locate.c \
   $$PWD/ext/zip/lib/zip_new.c \
   $$PWD/ext/zip/lib/zip_open.c \
   $$PWD/ext/zip/lib/zip_rename.c \
   $$PWD/ext/zip/lib/zip_replace.c \
   $$PWD/ext/zip/lib/zip_set_archive_comment.c \
   $$PWD/ext/zip/lib/zip_set_archive_flag.c \
   $$PWD/ext/zip/lib/zip_set_default_password.c \
   $$PWD/ext/zip/lib/zip_set_file_comment.c \
   $$PWD/ext/zip/lib/zip_set_file_compression.c \
   $$PWD/ext/zip/lib/zip_set_name.c \
   $$PWD/ext/zip/lib/zip_source_begin_write.c \
   $$PWD/ext/zip/lib/zip_source_buffer.c \
   $$PWD/ext/zip/lib/zip_source_call.c \
   $$PWD/ext/zip/lib/zip_source_close.c \
   $$PWD/ext/zip/lib/zip_source_commit_write.c \
   $$PWD/ext/zip/lib/zip_source_crc.c \
   $$PWD/ext/zip/lib/zip_source_deflate.c \
   $$PWD/ext/zip/lib/zip_source_error.c \
   $$PWD/ext/zip/lib/zip_source_file.c \
   $$PWD/ext/zip/lib/zip_source_filep.c \
   $$PWD/ext/zip/lib/zip_source_free.c \
   $$PWD/ext/zip/lib/zip_source_function.c \
   $$PWD/ext/zip/lib/zip_source_is_deleted.c \
   $$PWD/ext/zip/lib/zip_source_layered.c \
   $$PWD/ext/zip/lib/zip_source_open.c \
   $$PWD/ext/zip/lib/zip_source_pkware.c \
   $$PWD/ext/zip/lib/zip_source_read.c \
   $$PWD/ext/zip/lib/zip_source_remove.c \
   $$PWD/ext/zip/lib/zip_source_rollback_write.c \
   $$PWD/ext/zip/lib/zip_source_seek.c \
   $$PWD/ext/zip/lib/zip_source_seek_write.c \
   $$PWD/ext/zip/lib/zip_source_stat.c \
   $$PWD/ext/zip/lib/zip_source_supports.c \
   $$PWD/ext/zip/lib/zip_source_tell.c \
   $$PWD/ext/zip/lib/zip_source_tell_write.c \
   $$PWD/ext/zip/lib/zip_source_win32a.c \
   $$PWD/ext/zip/lib/zip_source_win32handle.c \
   $$PWD/ext/zip/lib/zip_source_win32utf8.c \
   $$PWD/ext/zip/lib/zip_source_win32w.c \
   $$PWD/ext/zip/lib/zip_source_window.c \
   $$PWD/ext/zip/lib/zip_source_write.c \
   $$PWD/ext/zip/lib/zip_source_zip.c \
   $$PWD/ext/zip/lib/zip_source_zip_new.c \
   $$PWD/ext/zip/lib/zip_stat.c \
   $$PWD/ext/zip/lib/zip_stat_index.c \
   $$PWD/ext/zip/lib/zip_stat_init.c \
   $$PWD/ext/zip/lib/zip_strerror.c \
   $$PWD/ext/zip/lib/zip_string.c \
   $$PWD/ext/zip/lib/zip_unchange.c \
   $$PWD/ext/zip/lib/zip_unchange_all.c \
   $$PWD/ext/zip/lib/zip_unchange_archive.c \
   $$PWD/ext/zip/lib/zip_unchange_data.c \
   $$PWD/ext/zip/lib/zip_utf-8.c \
   $$PWD/ext/zip/php_zip.c \
   $$PWD/ext/zip/zip_stream.c \
   $$PWD/ext/zlib/zlib.c \
   $$PWD/ext/zlib/zlib_filter.c \
   $$PWD/ext/zlib/zlib_fopen_wrapper.c \
   $$PWD/main/streams/cast.c \
   $$PWD/main/streams/filter.c \
   $$PWD/main/streams/glob_wrapper.c \
   $$PWD/main/streams/memory.c \
   $$PWD/main/streams/mmap.c \
   $$PWD/main/streams/plain_wrapper.c \
   $$PWD/main/streams/streams.c \
   $$PWD/main/streams/transports.c \
   $$PWD/main/streams/userspace.c \
   $$PWD/main/streams/xp_socket.c \
   $$PWD/main/alloca.c \
   $$PWD/main/explicit_bzero.c \
   $$PWD/main/fastcgi.c \
   $$PWD/main/fopen_wrappers.c \
   $$PWD/main/getopt.c \
   $$PWD/main/internal_functions.c \
   $$PWD/main/internal_functions_cli.c \
   $$PWD/main/internal_functions_win32.c \
   $$PWD/main/main.c \
   $$PWD/main/mergesort.c \
   $$PWD/main/network.c \
   $$PWD/main/output.c \
   $$PWD/main/php_content_types.c \
   $$PWD/main/php_ini.c \
   $$PWD/main/php_open_temporary_file.c \
   $$PWD/main/php_scandir.c \
   $$PWD/main/php_sprintf.c \
   $$PWD/main/php_ticks.c \
   $$PWD/main/php_variables.c \
   $$PWD/main/reentrancy.c \
   $$PWD/main/rfc1867.c \
   $$PWD/main/SAPI.c \
   $$PWD/main/snprintf.c \
   $$PWD/main/spprintf.c \
   $$PWD/main/strlcat.c \
   $$PWD/main/strlcpy.c \
   $$PWD/sapi/apache2handler/apache_config.c \
   $$PWD/sapi/apache2handler/mod_php7.c \
   $$PWD/sapi/apache2handler/php_functions.c \
   $$PWD/sapi/apache2handler/sapi_apache2.c \
   $$PWD/sapi/cgi/cgi_main.c \
   $$PWD/sapi/cli/cli_win32.c \
   $$PWD/sapi/cli/php_cli.c \
   $$PWD/sapi/cli/php_cli_process_title.c \
   $$PWD/sapi/cli/php_cli_server.c \
   $$PWD/sapi/cli/php_http_parser.c \
   $$PWD/sapi/cli/ps_title.c \
   $$PWD/sapi/embed/php_embed.c \
   $$PWD/sapi/fpm/fpm/events/devpoll.c \
   $$PWD/sapi/fpm/fpm/events/epoll.c \
   $$PWD/sapi/fpm/fpm/events/kqueue.c \
   $$PWD/sapi/fpm/fpm/events/poll.c \
   $$PWD/sapi/fpm/fpm/events/port.c \
   $$PWD/sapi/fpm/fpm/events/select.c \
   $$PWD/sapi/fpm/fpm/fpm.c \
   $$PWD/sapi/fpm/fpm/fpm_children.c \
   $$PWD/sapi/fpm/fpm/fpm_cleanup.c \
   $$PWD/sapi/fpm/fpm/fpm_clock.c \
   $$PWD/sapi/fpm/fpm/fpm_conf.c \
   $$PWD/sapi/fpm/fpm/fpm_env.c \
   $$PWD/sapi/fpm/fpm/fpm_events.c \
   $$PWD/sapi/fpm/fpm/fpm_log.c \
   $$PWD/sapi/fpm/fpm/fpm_main.c \
   $$PWD/sapi/fpm/fpm/fpm_php.c \
   $$PWD/sapi/fpm/fpm/fpm_php_trace.c \
   $$PWD/sapi/fpm/fpm/fpm_process_ctl.c \
   $$PWD/sapi/fpm/fpm/fpm_request.c \
   $$PWD/sapi/fpm/fpm/fpm_scoreboard.c \
   $$PWD/sapi/fpm/fpm/fpm_shm.c \
   $$PWD/sapi/fpm/fpm/fpm_signals.c \
   $$PWD/sapi/fpm/fpm/fpm_sockets.c \
   $$PWD/sapi/fpm/fpm/fpm_status.c \
   $$PWD/sapi/fpm/fpm/fpm_stdio.c \
   $$PWD/sapi/fpm/fpm/fpm_systemd.c \
   $$PWD/sapi/fpm/fpm/fpm_trace.c \
   $$PWD/sapi/fpm/fpm/fpm_trace_mach.c \
   $$PWD/sapi/fpm/fpm/fpm_trace_pread.c \
   $$PWD/sapi/fpm/fpm/fpm_trace_ptrace.c \
   $$PWD/sapi/fpm/fpm/fpm_unix.c \
   $$PWD/sapi/fpm/fpm/fpm_worker_pool.c \
   $$PWD/sapi/fpm/fpm/zlog.c \
   $$PWD/sapi/litespeed/lsapi_main.c \
   $$PWD/sapi/litespeed/lsapilib.c \
   $$PWD/sapi/litespeed/lscriu.c \
   $$PWD/sapi/phpdbg/phpdbg.c \
   $$PWD/sapi/phpdbg/phpdbg_bp.c \
   $$PWD/sapi/phpdbg/phpdbg_break.c \
   $$PWD/sapi/phpdbg/phpdbg_btree.c \
   $$PWD/sapi/phpdbg/phpdbg_cmd.c \
   $$PWD/sapi/phpdbg/phpdbg_eol.c \
   $$PWD/sapi/phpdbg/phpdbg_frame.c \
   $$PWD/sapi/phpdbg/phpdbg_help.c \
   $$PWD/sapi/phpdbg/phpdbg_info.c \
   $$PWD/sapi/phpdbg/phpdbg_io.c \
   $$PWD/sapi/phpdbg/phpdbg_lexer.c \
   $$PWD/sapi/phpdbg/phpdbg_list.c \
   $$PWD/sapi/phpdbg/phpdbg_opcode.c \
   $$PWD/sapi/phpdbg/phpdbg_out.c \
   $$PWD/sapi/phpdbg/phpdbg_parser.c \
   $$PWD/sapi/phpdbg/phpdbg_print.c \
   $$PWD/sapi/phpdbg/phpdbg_prompt.c \
   $$PWD/sapi/phpdbg/phpdbg_rinit_hook.c \
   $$PWD/sapi/phpdbg/phpdbg_set.c \
   $$PWD/sapi/phpdbg/phpdbg_sigio_win32.c \
   $$PWD/sapi/phpdbg/phpdbg_sigsafe.c \
   $$PWD/sapi/phpdbg/phpdbg_utils.c \
   $$PWD/sapi/phpdbg/phpdbg_wait.c \
   $$PWD/sapi/phpdbg/phpdbg_watch.c \
   $$PWD/sapi/phpdbg/phpdbg_webdata_transfer.c \
   $$PWD/sapi/phpdbg/phpdbg_win.c \
   $$PWD/TSRM/TSRM.c \
   $$PWD/TSRM/tsrm_strtok_r.c \
   $$PWD/TSRM/tsrm_win32.c \
   $$PWD/win32/build/deplister.c \
   $$PWD/win32/codepage.c \
   $$PWD/win32/console.c \
   $$PWD/win32/cp_enc_map.c \
   $$PWD/win32/cp_enc_map_gen.c \
   $$PWD/win32/dllmain.c \
   $$PWD/win32/fnmatch.c \
   $$PWD/win32/ftok.c \
   $$PWD/win32/getrusage.c \
   $$PWD/win32/glob.c \
   $$PWD/win32/globals.c \
   $$PWD/win32/inet.c \
   $$PWD/win32/ioutil.c \
   $$PWD/win32/nice.c \
   $$PWD/win32/readdir.c \
   $$PWD/win32/registry.c \
   $$PWD/win32/select.c \
   $$PWD/win32/sendmail.c \
   $$PWD/win32/sockets.c \
   $$PWD/win32/time.c \
   $$PWD/win32/winutil.c \
   $$PWD/win32/wsyslog.c \
   $$PWD/Zend/zend.c \
   $$PWD/Zend/zend_alloc.c \
   $$PWD/Zend/zend_API.c \
   $$PWD/Zend/zend_ast.c \
   $$PWD/Zend/zend_builtin_functions.c \
   $$PWD/Zend/zend_closures.c \
   $$PWD/Zend/zend_compile.c \
   $$PWD/Zend/zend_constants.c \
   $$PWD/Zend/zend_default_classes.c \
   $$PWD/Zend/zend_dtrace.c \
   $$PWD/Zend/zend_exceptions.c \
   $$PWD/Zend/zend_execute.c \
   $$PWD/Zend/zend_execute_API.c \
   $$PWD/Zend/zend_extensions.c \
   $$PWD/Zend/zend_float.c \
   $$PWD/Zend/zend_gc.c \
   $$PWD/Zend/zend_generators.c \
   $$PWD/Zend/zend_hash.c \
   $$PWD/Zend/zend_highlight.c \
   $$PWD/Zend/zend_inheritance.c \
   $$PWD/Zend/zend_ini.c \
   $$PWD/Zend/zend_ini_parser.c \
   $$PWD/Zend/zend_ini_scanner.c \
   $$PWD/Zend/zend_interfaces.c \
   $$PWD/Zend/zend_iterators.c \
   $$PWD/Zend/zend_language_parser.c \
   $$PWD/Zend/zend_language_scanner.c \
   $$PWD/Zend/zend_list.c \
   $$PWD/Zend/zend_llist.c \
   $$PWD/Zend/zend_multibyte.c \
   $$PWD/Zend/zend_object_handlers.c \
   $$PWD/Zend/zend_objects.c \
   $$PWD/Zend/zend_objects_API.c \
   $$PWD/Zend/zend_opcode.c \
   $$PWD/Zend/zend_operators.c \
   $$PWD/Zend/zend_ptr_stack.c \
   $$PWD/Zend/zend_signal.c \
   $$PWD/Zend/zend_smart_str.c \
   $$PWD/Zend/zend_sort.c \
   $$PWD/Zend/zend_sprintf.c \
   $$PWD/Zend/zend_stack.c \
   $$PWD/Zend/zend_stream.c \
   $$PWD/Zend/zend_string.c \
   $$PWD/Zend/zend_strtod.c \
   $$PWD/Zend/zend_ts_hash.c \
   $$PWD/Zend/zend_variables.c \
   $$PWD/Zend/zend_virtual_cwd.c \
   $$PWD/Zend/zend_vm_opcodes.c

INCLUDEPATH = \
    $$PWD/ext/bcmath \
    $$PWD/ext/bcmath/libbcmath \
    $$PWD/ext/bcmath/libbcmath/src \
    $$PWD/ext/bz2 \
    $$PWD/ext/calendar \
    $$PWD/ext/com_dotnet \
    $$PWD/ext/ctype \
    $$PWD/ext/curl \
    $$PWD/ext/date \
    $$PWD/ext/date/lib \
    $$PWD/ext/dba \
    $$PWD/ext/dba/libcdb \
    $$PWD/ext/dba/libflatfile \
    $$PWD/ext/dba/libinifile \
    $$PWD/ext/dom \
    $$PWD/ext/enchant \
    $$PWD/ext/exif \
    $$PWD/ext/fileinfo \
    $$PWD/ext/fileinfo/libmagic \
    $$PWD/ext/filter \
    $$PWD/ext/ftp \
    $$PWD/ext/gd \
    $$PWD/ext/gd/libgd \
    $$PWD/ext/gettext \
    $$PWD/ext/gmp \
    $$PWD/ext/hash \
    $$PWD/ext/hash/sha3/generic32lc \
    $$PWD/ext/hash/sha3/generic64lc \
    $$PWD/ext/iconv \
    $$PWD/ext/iconv/ext/iconv \
    $$PWD/ext/imap \
    $$PWD/ext/interbase \
    $$PWD/ext/intl \
    $$PWD/ext/intl/breakiterator \
    $$PWD/ext/intl/calendar \
    $$PWD/ext/intl/collator \
    $$PWD/ext/intl/common \
    $$PWD/ext/intl/converter \
    $$PWD/ext/intl/dateformat \
    $$PWD/ext/intl/formatter \
    $$PWD/ext/intl/grapheme \
    $$PWD/ext/intl/idn \
    $$PWD/ext/intl/locale \
    $$PWD/ext/intl/msgformat \
    $$PWD/ext/intl/normalizer \
    $$PWD/ext/intl/resourcebundle \
    $$PWD/ext/intl/spoofchecker \
    $$PWD/ext/intl/timezone \
    $$PWD/ext/intl/transliterator \
    $$PWD/ext/intl/uchar \
    $$PWD/ext/json \
    $$PWD/ext/ldap \
    $$PWD/ext/libxml \
    $$PWD/ext/mbstring \
    $$PWD/ext/mbstring/libmbfl \
    $$PWD/ext/mbstring/libmbfl/filters \
    $$PWD/ext/mbstring/libmbfl/mbfl \
    $$PWD/ext/mbstring/libmbfl/nls \
    $$PWD/ext/mbstring/oniguruma \
    $$PWD/ext/mbstring/oniguruma/src \
    $$PWD/ext/mysqli \
    $$PWD/ext/mysqlnd \
    $$PWD/ext/oci8 \
    $$PWD/ext/odbc \
    $$PWD/ext/opcache \
    $$PWD/ext/opcache/Optimizer \
    $$PWD/ext/openssl \
    $$PWD/ext/pcntl \
    $$PWD/ext/pcre \
    $$PWD/ext/pcre/pcrelib \
    $$PWD/ext/pcre/pcrelib/sljit \
    $$PWD/ext/pdo \
    $$PWD/ext/pdo_dblib \
    $$PWD/ext/pdo_firebird \
    $$PWD/ext/pdo_mysql \
    $$PWD/ext/pdo_oci \
    $$PWD/ext/pdo_odbc \
    $$PWD/ext/pdo_pgsql \
    $$PWD/ext/pdo_sqlite \
    $$PWD/ext/pgsql \
    $$PWD/ext/phar \
    $$PWD/ext/posix \
    $$PWD/ext/pspell \
    $$PWD/ext/readline \
    $$PWD/ext/recode \
    $$PWD/ext/reflection \
    $$PWD/ext/session \
    $$PWD/ext/shmop \
    $$PWD/ext/simplexml \
    $$PWD/ext/skeleton \
    $$PWD/ext/snmp \
    $$PWD/ext/soap \
    $$PWD/ext/sockets \
    $$PWD/ext/sodium \
    $$PWD/ext/spl \
    $$PWD/ext/sqlite3 \
    $$PWD/ext/sqlite3/libsqlite \
    $$PWD/ext/standard \
    $$PWD/ext/sysvmsg \
    $$PWD/ext/sysvsem \
    $$PWD/ext/sysvshm \
    $$PWD/ext/tidy \
    $$PWD/ext/tokenizer \
    $$PWD/ext/wddx \
    $$PWD/ext/xml \
    $$PWD/ext/xmlreader \
    $$PWD/ext/xmlrpc \
    $$PWD/ext/xmlrpc/libxmlrpc \
    $$PWD/ext/xmlwriter \
    $$PWD/ext/xsl \
    $$PWD/ext/zend_test \
    $$PWD/ext/zip \
    $$PWD/ext/zip/lib \
    $$PWD/ext/zlib \
    $$PWD/main \
    $$PWD/main/streams \
    $$PWD/sapi/apache2handler \
    $$PWD/sapi/cli \
    $$PWD/sapi/embed \
    $$PWD/sapi/fpm \
    $$PWD/sapi/fpm/fpm \
    $$PWD/sapi/fpm/fpm/events \
    $$PWD/sapi/litespeed \
    $$PWD/sapi/phpdbg \
    $$PWD/TSRM \
    $$PWD/win32 \
    $$PWD/Zend

#DEFINES = 

