iconv.lo: /Users/momo/helloworld/php/php-src/ext/iconv/iconv.c
	$(LIBTOOL) --mode=compile $(CC) -I"/usr/local/Cellar/libiconv/1.15/include" -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/Users/momo/helloworld/php/php-src/ext/iconv $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/momo/helloworld/php/php-src/ext/iconv/iconv.c -o iconv.lo 
$(phplibdir)/iconv.la: ./iconv.la
	$(LIBTOOL) --mode=install cp ./iconv.la $(phplibdir)

./iconv.la: $(shared_objects_iconv) $(ICONV_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_iconv) $(ICONV_SHARED_LIBADD)

